module.exports = [
	{
		"S.No": "1",
		"Nature of job": "Postdoc Research Fellow",
		Name: "Postdoc Research Fellow in Civil/Structural Engineering",
		University: "Zhejiang University",
		Country: "Hangzhou, China",
		"Application End Date": "June 28, 2021",
		Website:
			"https://www.timeshighereducation.com/unijobs/listing/253128/postdoc-research-fellow-in-civil-structural-engineering/?LinkSource=PremiumListing",
	},
	{
		"S.No": "2",
		"Nature of job": "Postdoctoral Researcher Fellow",
		Name: "Postdoctoral Researcher Fellow in Industrial Systems Safety, Optimization and Control",
		University: "Zhejiang University",
		Country: "Hangzhou, China",
		"Application End Date": "June 28, 2021",
		Website:
			"https://www.timeshighereducation.com/unijobs/listing/253127/postdoctoral-researcher-fellow-in-industrial-systems-safety-optimization-and-control/?LinkSource=PremiumListing",
	},
	{
		"S.No": "3",
		"Nature of job": "Postdoctoral Research Fellow",
		Name: "Postdoctoral Research Fellow in Plant Phenotyping",
		University: "Zhejiang University",
		Country: "Hangzhou, China",
		"Application End Date": "June 28, 2021",
		Website:
			"https://www.timeshighereducation.com/unijobs/listing/253121/postdoctoral-research-fellow-in-plant-phenotyping/?LinkSource=PremiumListing",
	},
	{
		"S.No": "4",
		"Nature of job": "Postdoctoral Research Fellow",
		Name: "Postdoctoral Fellowship Program, Researcher in Intelligent Molecule and Material Discovery",
		University: "Zhejiang University",
		Country: "Hangzhou, China",
		"Application End Date": "June 28, 2021",
		Website:
			"https://www.timeshighereducation.com/unijobs/listing/253113/postdoctoral-fellowship-program-researcher-in-intelligent-molecule-and-material-discovery/?LinkSource=PremiumListing",
	},
	{
		"S.No": "5",
		"Nature of job": "Postdoctoral Fellowship Program",
		Name: "Postdoctoral Fellowship Program, Recruiting Researcher in Synthetic Biology",
		University: "Zhejiang University",
		Country: "Hangzhou, China",
		"Application End Date": "June 28, 2021",
		Website:
			"https://www.timeshighereducation.com/unijobs/listing/253112/postdoctoral-fellowship-program-recruiting-researcher-in-synthetic-biology/?LinkSource=PremiumListing",
	},
	{
		"S.No": "6",
		"Nature of job": "Postdoctoral Fellow",
		Name: "Postdoctoral Fellow in Medicine",
		University: "Zhejiang University",
		Country: "Hangzhou, China",
		"Application End Date": "June 28, 2021",
		Website:
			"https://www.timeshighereducation.com/unijobs/listing/253105/postdoctoral-fellow-in-medicine/?LinkSource=PremiumListing",
	},
	{
		"S.No": "7",
		"Nature of job": "Postdoc Fellow",
		Name: "Post-doctoral Fellow, Department of Electrical and Electronic Engineering",
		University: "The University of Hong Kong",
		Country: "Pok Fu Lam, Hong Kong",
		"Application End Date": "October 31, 2021",
		Website:
			"https://www.timeshighereducation.com/unijobs/listing/253056/post-doctoral-fellow-department-of-electrical-and-electronic-engineering/?LinkSource=PremiumListing",
	},
	{
		"S.No": "8",
		"Nature of job": "Postdoc Fellow",
		Name: "Post-doctoral Fellow, School of Public Health",
		University: "The University of Hong Kong",
		Country: "Pok Fu Lam, Hong Kong",
		"Application End Date": "August 31, 2021",
		Website:
			"https://www.timeshighereducation.com/unijobs/listing/252948/post-doctoral-fellow-school-of-public-health/?LinkSource=PremiumListing",
	},
	{
		"S.No": "9",
		"Nature of job": "Postdoc Fellow",
		Name: "Post-doctoral Fellow in Cancer Biology",
		University: "The University of Hong Kong",
		Country: "Pok Fu Lam, Hong Kong",
		"Application End Date": "August 31, 2021",
		Website:
			"https://www.timeshighereducation.com/unijobs/listing/252863/post-doctoral-fellow-in-cancer-biology/?LinkSource=PremiumListing",
	},
	{
		"S.No": "10",
		"Nature of job": "PhD Studentship",
		Name: "PhD Studentship, Metallic Cylinders for Safe Storage of Hydrogen Fuel Onboard Ships",
		University: "University of Southampton",
		Country: "Southampton, UK",
		"Application End Date": "August 31, 2021",
		Website:
			"https://www.timeshighereducation.com/unijobs/listing/251246/phd-studentship-metallic-cylinders-for-safe-storage-of-hydrogen-fuel-onboard-ships/?LinkSource=PremiumListing",
	},
	{
		"S.No": "11",
		"Nature of job": "PhD Studentship",
		Name: "PhD Studentship, Modelling Resilience in Automated Transport Systems with Human Factors Methods",
		University: "University of Southampton",
		Country: "Southampton, UK",
		"Application End Date": "July 31, 2021",
		Website:
			"https://www.timeshighereducation.com/unijobs/listing/251074/phd-studentship-modelling-resilience-in-automated-transport-systems-with-human-factors-methods/?LinkSource=PremiumListing",
	},
	{
		"S.No": "12",
		"Nature of job": "PhD Studentship",
		Name: "PhD Studentship, Silicon Photonics for Ocean Pollutant Monitoring",
		University: "University of Southampton",
		Country: "Southampton, UK",
		"Application End Date": "August 31, 2021",
		Website:
			"https://www.timeshighereducation.com/unijobs/listing/250854/phd-studentship-silicon-photonics-for-ocean-pollutant-monitoring/?LinkSource=SimilarJobPlatform",
	},
	{
		"S.No": "13",
		"Nature of job": "PhD Studentship",
		Name: "Mechanical Engineering",
		University: "University of Maryland Baltimore County (UMBC)",
		Country: "Baltimore, USA",
		"Application End Date": "Before Sep 2021",
		Website: "https://www.phdportal.com/studies/304726/mechanical-engineering.html#content:key_facts",
	},
	{
		"S.No": "14",
		"Nature of job": "PhD Studentship",
		Name: "Mechanical Engineering",
		University: "South Dakota State University",
		Country: "South Dakota, USA",
		"Application End Date": "Before Aug 2021",
		Website: "https://www.phdportal.com/studies/303702/mechanical-engineering.html",
	},
	{
		"S.No": "15",
		"Nature of job": "PhD Studentship",
		Name: "Mechanical Engineering",
		University: "University at Buffalo SUNY - School of Engineering and Applied Sciences",
		Country: "New York, USA",
		"Application End Date": "Before Dec 2021",
		Website: "https://www.phdportal.com/studies/152861/mechanical-engineering.html",
	},
	{
		"S.No": "16",
		"Nature of job": "PhD Studentship",
		Name: "Mechanical Engineering",
		University: "University of Oklahoma",
		Country: "Oklahoma, USA",
		"Application End Date": "Before Sep 2021",
		Website: "https://www.phdportal.com/studies/233840/mechanical-engineering.html",
	},
	{
		"S.No": "17",
		"Nature of job": "Funded PhD",
		Name: "Cybernetic System and Control",
		University: "Arizona State University",
		Country: "Arizona, USA",
		"Application End Date": "Till position filled",
		Website: "https://www.findaphd.com/phds/project/phd-position-in-cybernetic-systems-and-control/?p132128",
	},
	{
		"S.No": "18",
		"Nature of job": "Funded PhD",
		Name: "Bio-inspired morphing solutions for aeroelastic problems",
		University: "University of Liverpool",
		Country: "Liverpool, UK",
		"Application End Date": "July 15, 2021",
		Website:
			"https://www.findaphd.com/phds/project/bio-inspired-morphing-solutions-for-aeroelastic-problems/?p132086",
	},
	{
		"S.No": "19",
		"Nature of job": "Funded PhD",
		Name: "AI Fellowships for PhD in Computer Science and Engineering",
		University: "KOÇ UNIVERSITY",
		Country: "Sariyer Istanbul, Turkey",
		"Application End Date": "June 18, 2021",
		Website:
			"https://academicpositions.com/ad/koc-university/2021/koc-university-ai-fellowships-for-phd-in-computer-science-and-engineering-koc-university-is-bankasi-artificial-intelligence-research-center-kuis-ai-fall-2021-admission/157783",
	},
	{
		"S.No": "20",
		"Nature of job": "Funded PhD",
		Name: "19 fully funded PhD positions in Inorganic materials and technology, 4- years study at FunGlass",
		University: "FUNGLASS",
		Country: "Trenčín, Slovakia",
		"Application End Date": "July 30, 2021",
		Website:
			"https://academicpositions.com/ad/funglass/2021/19-fully-funded-phd-positions-in-inorganic-materials-and-technology-4-years-study-at-funglass/157459",
	},
	{
		"S.No": "21",
		"Nature of job": "Funded PhD",
		Name: "PhD Student in Deep Learning for Acoustic Monitoring",
		University: "ETH Zurich",
		Country: "Rämistrasse 101, 8006 Zurich",
		Website:
			"https://academicpositions.com/ad/eth-zurich/2021/phd-student-in-deep-learning-for-acoustic-monitoring/158021",
	},
	{
		"S.No": "22",
		"Nature of job": "Self-Funded PhD",
		Name: "Buildings, energy and professional ways of thinking",
		University: "University of Reading",
		Country: "Reading, UK",
		"Application End Date": "Till position filled",
		Website: "https://www.findaphd.com/phds/project/buildings-energy-and-professional-ways-of-thinking/?p132236",
	},
	{
		"S.No": "23",
		"Nature of job": "Self-Funded PhD",
		Name: "Decarbonisation of heating and cooling",
		University: "University of Reading",
		Country: "Reading, UK",
		"Application End Date": "Till position filled",
		Website: "https://www.findaphd.com/phds/project/decarbonisation-of-heating-and-cooling/?p132232",
	},
	{
		"S.No": "24",
		"Nature of job": "Funded PhD",
		Name: "Modelling and simulation of the nuclear reactors using advanced multiscale/multiphysics methods",
		University: "University of Liverpool",
		Country: "Liverpool, UK",
		"Application End Date": "May 30, 2021",
		Website:
			"https://www.findaphd.com/phds/project/modelling-and-simulation-of-the-nuclear-reactors-using-advanced-multiscale-multiphysics-methods/?p132229",
	},
	{
		"S.No": "25",
		"Nature of job": "Funded PhD",
		Name: "Synthesis of “smart” polymer nanostructured materials for use in food research - WP3, WP2",
		University: "Aristotle University of Thessaloniki",
		Country: "Greece",
		"Application End Date": "June 30, 2021",
		Website:
			"https://www.findaphd.com/phds/project/synthesis-of-smart-polymer-nanostructured-materials-for-use-in-food-research-wp3-wp2/?p132504",
	},
	{
		"S.No": "26",
		"Nature of job": "Funded PhD",
		Name: "Alternative waste exploitation: micro and nano-plastic in agricultural wastewater reuse - WP2",
		University: "The Jožef Stefan Institute",
		Country: "Ljubljana, Slovenia",
		"Application End Date": "June 30, 2021",
		Website:
			"https://www.findaphd.com/phds/project/alternative-waste-exploitation-micro-and-nano-plastic-in-agricultural-wastewater-reuse-wp2/?p132501",
	},
	{
		"S.No": "27",
		"Nature of job": "Funded PhD",
		Name: "Novel strategies for verifying food authenticity and build consumer trust – WP5",
		University: "The Jožef Stefan Institute",
		Country: "Ljubljana, Slovenia",
		"Application End Date": "June 30, 2021",
		Website:
			"https://www.findaphd.com/phds/project/novel-strategies-for-verifying-food-authenticity-and-build-consumer-trust-wp5/?p132500",
	},
	{
		"S.No": "28",
		"Nature of job": "Funded PhD",
		Name: "Characterisation of bioactive compounds in organic beekeeping - WP1",
		University: "Spanish National Research Council",
		Country: "Madrid, Spain",
		"Application End Date": "June 30, 2021",
		Website:
			"https://www.findaphd.com/phds/project/characterisation-of-bioactive-compounds-in-organic-beekeeping-wp1/?p132499",
	},
	{
		"S.No": "29",
		"Nature of job": "Funded PhD",
		Name: "Authenticity of dairy products - WP2, WP1",
		University: "Fondazione Edmund Mach (FEM)",
		Country: "Trentino, Italy",
		"Application End Date": "June 30, 2021",
		Website: "https://www.findaphd.com/phds/project/authenticity-of-dairy-products-wp2-wp1/?p132495",
	},
	{
		"S.No": "30",
		"Nature of job": "Funded PhD",
		Name: "Markers for pasta and organic rice authentication - WP1, WP2",
		University: "Fondazione Edmund Mach (FEM)",
		Country: "Trentino, Italy",
		"Application End Date": "June 30, 2021",
		Website:
			"https://www.findaphd.com/phds/project/markers-for-pasta-and-organic-rice-authentication-wp1-wp2/?p132493",
	},
	{
		"S.No": "31",
		"Nature of job": "Funded PhD",
		Name: "Soil as a core infrastructure to support catchment and water supply resilience PhD",
		University: "Cranfield University",
		Country: "Cranfield, UK",
		"Application End Date": "June 30, 2021",
		Website:
			"https://www.findaphd.com/phds/project/soil-as-a-core-infrastructure-to-support-catchment-and-water-supply-resilience-phd/?p130565",
	},
	{
		"S.No": "32",
		"Nature of job": "Funded PhD",
		Name: "Engineering light-matter interactions with 2D materials at the nanometer level via substrate patterning",
		University: "Italian Institute of Technology",
		Country: "Genoa, Italy",
		"Application End Date": "June 15, 2021",
		Website:
			"https://www.findaphd.com/phds/project/engineering-light-matter-interactions-with-2d-materials-at-the-nanometer-level-via-substrate-patterning/?p132488",
	},
	{
		"S.No": "33",
		"Nature of job": "Funded PhD",
		Name: "Development of low-dimensional material based light-driven nanoscale devices",
		University: "Italian Institute of Technology",
		Country: "Genoa, Italy",
		"Application End Date": "June 15, 2021",
		Website:
			"https://www.findaphd.com/phds/project/development-of-low-dimensional-material-based-light-driven-nanoscale-devices/?p132483",
	},
	{
		"S.No": "34",
		"Nature of job": "Funded PhD",
		Name: "Development of low-dimensional material based light-driven nanoscale device",
		University: "Italian Institute of Technology",
		Country: "Genoa, Italy",
		"Application End Date": "June 15, 2021",
		Website:
			"https://www.findaphd.com/phds/project/development-of-low-dimensional-material-based-light-driven-nanoscale-devices/?p132483",
	},
	{
		"S.No": "35",
		"Nature of job": "Funded PhD",
		Name: "Contingency Management of Future Advanced Air Mobility System PhD",
		University: "Cranfield University",
		Country: "Cranfield, UK",
		"Application End Date": "July 05, 2021",
		Website:
			"https://www.findaphd.com/phds/project/contingency-management-of-future-advanced-air-mobility-system-phd/?p132477",
	},
	{
		"S.No": "36",
		"Nature of job": "Funded PhD",
		Name: "Enabling 'go-hard, go-early' for novel pathogen incursion using electrical and molecular detection tools",
		University: "University of Canterbury",
		Country: "Christchurch, New Zealand",
		"Application End Date": "Till position filled",
		Website:
			"https://www.findaphd.com/phds/project/enabling-go-hard-go-early-for-novel-pathogen-incursion-using-electrical-and-molecular-detection-tools/?p132476",
	},
	{
		"S.No": "37",
		"Nature of job": "Funded PhD",
		Name: "Microfluidic assays for in-field pathogen detection",
		University: "University of Canterbury",
		Country: "Christchurch, New Zealand",
		"Application End Date": "Till position filled",
		Website: "https://www.findaphd.com/phds/project/microfluidic-assays-for-in-field-pathogen-detection/?p132474",
	},
	{
		"S.No": "38",
		"Nature of job": "Funded PhD",
		Name: "Recent Advancements on Life Cycle Assessment",
		University: "University of Huddersfield",
		Country: "Huddersfield, England",
		"Application End Date": "June 30, 2021",
		Website: "https://www.findaphd.com/phds/project/recent-advancements-on-life-cycle-assessment/?p132467",
	},
	{
		"S.No": "39",
		"Nature of job": "Funded PhD",
		Name: "Nanoprobe-based screening method for the detection of plant pathogens",
		University: "Forschungszentrum Jülich",
		Country: "Jülich, Germany",
		"Application End Date": "June 30, 2021",
		Website:
			"https://www2.daad.de/deutschland/promotion/phd/en/13306-phdgermany-database/?promotiontype=&subject=5386&workinglang=5391&town=&paid=5405&q=&page=1&sorting=created&detail=5949",
	},
	{
		"S.No": "40",
		"Nature of job": "Funded PhD",
		Name: "Software-Defined Wireless Networks for Mission-Critical Applications",
		University: "Technical University of Darmstadt",
		Country: "Darmstadt, Germany",
		"Application End Date": "June 18, 2021",
		Website:
			"https://www2.daad.de/deutschland/promotion/phd/en/13306-phdgermany-database/?promotiontype=&subject=5386&workinglang=5391&town=&paid=5405&q=&page=1&sorting=created&detail=5947",
	},
	{
		"S.No": "41",
		"Nature of job": "Funded PhD",
		Name: "Strong-field THz generation",
		University: "German Electron Synchrotron DESY",
		Country: "Hamburg, Germany",
		"Application End Date": "June 15, 2021",
		Website:
			"https://www2.daad.de/deutschland/promotion/phd/en/13306-phdgermany-database/?promotiontype=&subject=5386&workinglang=5391&town=&paid=5405&q=&page=2&sorting=created&detail=5923",
	},
	{
		"S.No": "42",
		"Nature of job": "Funded PhD",
		Name: "high throughput component tests in proton exchange membrane electrolysers",
		University: "Forschungszentrum Jülich",
		Country: "Jülich, Germany",
		"Application End Date": "June 27, 2021",
		Website:
			"https://www2.daad.de/deutschland/promotion/phd/en/13306-phdgermany-database/?promotiontype=&subject=5386&workinglang=5391&town=&paid=5405&q=&page=2&sorting=created&detail=5914",
	},
	{
		"S.No": "43",
		"Nature of job": "Funded PhD",
		Name: "PHD position in Cybernetic Systems and Control",
		University: "Arizona State University, Tempe",
		Country: "Arizona, USA",
		"Application End Date": "Till position filled",
		Website: "https://www.findaphd.com/phds/project/phd-position-in-cybernetic-systems-and-control/?p132128",
	},
	{
		"S.No": "44",
		"Nature of job": "Funded PhD",
		Name: "Computational Modeling on Catalytic CO2 Conversion",
		University: "Clarkson University",
		Country: "Potsdam, USA",
		"Application End Date": "Till position filled",
		Website: "https://www.findaphd.com/phds/project/computational-modeling-on-catalytic-co2-conversion/?p124800",
	},
	{
		"S.No": "45",
		"Nature of job": "Funded PhD",
		Name: "PhD Fellowships to study at Purdue University in CIT",
		University: "Purdue University",
		Country: "West Lafayette, USA",
		"Application End Date": "Fall 2021 or Spring 2022",
		Website: "https://www.findaphd.com/phds/programme/phd-fellowships-to-study-at-purdue-university-in-cit/?p5124",
	},
	{
		"S.No": "46",
		"Nature of job": "Funded PhD",
		Name: "PhD Position for H2020 Project ASTROTECH(GA no. 956325)",
		University: "BCAM – Basque Center for Applied Mathematics",
		Country: "Bilbao, Bizkaia, Spain",
		"Application End Date": "June 30, 2021",
		Website:
			"https://academicpositions.com/ad/bcam-basque-center-for-applied-mathematics/2021/phd-position-for-h2020-project-astrotech-ga-no-956325/158651",
	},
	{
		"S.No": "47",
		"Nature of job": "Funded PhD",
		Name: "PhD programs at the IMT School for Advanced Studies Lucca(various subjects)",
		University: "IMT School for Advanced Studies Lucca",
		Country: "Piazza S. Ponziano, Lucca",
		"Application End Date": "June 30, 2021",
		Website:
			"https://academicpositions.com/ad/imt-school-for-advanced-studies-lucca/2021/2021-22-phd-programs-at-the-imt-school-for-advanced-studies-lucca/158114",
	},
	{
		"S.No": "48",
		"Nature of job": "Funded PhD",
		Name: "Assistant (19361) - Data analysis and mathematical modelling",
		University: "GHENT UNIVERSITY",
		Country: "Sint-Pietersnieuwstraat, Belgium",
		"Application End Date": "June 22, 2021",
		Website:
			"https://academicpositions.com/ad/ghent-university/2021/assistant-19361-data-analysis-and-mathematical-modelling/159592",
	},
	{
		"S.No": "49",
		"Nature of job": "Funded PhD",
		Name: "junior Researcher (Doctoral Student) In High-Speed Electrical Motor Technology",
		University: "LUT University",
		Country: "Lappeenranta, Finland",
		"Application End Date": "June 20, 2021",
		Website:
			"https://academicpositions.com/ad/lut-university/2021/junior-researcher-doctoral-student-in-high-speed-electrical-motor-technology/159546",
	},
	{
		"S.No": "50",
		"Nature of job": "Funded PhD",
		Name: "PhD Student Position In Robot Learning",
		University: "Aalto University",
		Country: "Espoo, Finland",
		"Application End Date": "June 24, 2021",
		Website: "https://academicpositions.com/ad/aalto-university/2021/phd-student-position-in-robot-learning/159482",
	},
	{
		"S.No": "51",
		"Nature of job": "Funded PhD",
		Name: "PhD Position – Audio Signal Enhancement",
		University: "Fraunhofer IDMT, Oldenburg",
		Country: "Oldenburg, Germany",
		"Application End Date": "June 15, 2021",
		Website:
			"https://academicpositions.com/ad/fraunhofer-idmt-oldenburg/2021/phd-position-audio-signal-enhancement/159464",
	},
];
