module.exports = [
	{
		"S.No": "1",
		"Nature of job": "Funded PhD",
		Name: "Mechanics of soft solids and structures under large deformation",
		University: "University of Glasgow",
		Country: "Glasgow, Scotland",
		"Application End Date": "Till position filled",
		Website:
			"https://www.findaphd.com/phds/project/mechanics-of-soft-solids-and-structures-under-large-deformation/?p110371",
	},
	{
		"S.No": "2",
		"Nature of job": "Funded PhD",
		Name: "Hydrogen Ventilation in a Geological Disposal Facility",
		University: "University of Bristol",
		Country: "Bristol, England",
		"Application End Date": "8/25/21",
		Website:
			"https://www.findaphd.com/phds/project/hydrogen-ventilation-in-a-geological-disposal-facility/?p130831",
	},
	{
		"S.No": "3",
		"Nature of job": "Funded PhD",
		Name: "Hybrid Electric Aircraft Propulsion: Systems and Architectures Integration PhD",
		University: "Cranfield University",
		Country: "Cranfield, England",
		"Application End Date": "9/2/21",
		Website:
			"https://www.findaphd.com/phds/project/hybrid-electric-aircraft-propulsion-systems-and-architectures-integration-phd/?p134055",
	},
	{
		"S.No": "4",
		"Nature of job": "Funded PhD",
		Name: "Microbially driven recycling of nutrients from recovered VBS plants/fungi through Green manure and Biochar.",
		University: "Trinity College Dublin",
		Country: "Dublin, Ireland",
		"Application End Date": "8/31/21",
		Website:
			"https://www.findaphd.com/phds/project/microbially-driven-recycling-of-nutrients-from-recovered-vbs-plants-fungi-through-green-manure-and-biochar/?p134054",
	},
	{
		"S.No": "5",
		"Nature of job": "Funded PhD",
		Name: "Investigating a nature-based solution for agricultural runoff in Ireland: Identification of nutrient/trace element accumulator plant species and their microbial interaction.",
		University: "Trinity College Dublin",
		Country: "Dublin, Ireland",
		"Application End Date": "11/30/21",
		Website:
			"https://www.findaphd.com/phds/project/investigating-a-nature-based-solution-for-agricultural-runoff-in-ireland-identification-of-nutrient-trace-element-accumulator-plant-species-and-their-microbial-interaction/?p134053",
	},
	{
		"S.No": "6",
		"Nature of job": "Funded PhD",
		Name: "Development of 360 audiovisual technology for monitoring biodiversity",
		University: "Trinity College Dublin",
		Country: "Dublin, Ireland",
		"Application End Date": "8/31/21",
		Website:
			"https://www.findaphd.com/phds/project/development-of-360-audiovisual-technology-for-monitoring-biodiversity/?p134049",
	},
	{
		"S.No": "7",
		"Nature of job": "Funded PhD",
		Name: "Thermodynamics and Rheology of Polymers in solution at RWTH Aachen University",
		University: "RWTH Aachen University",
		Country: "Aachen, Germany",
		"Application End Date": "9/2/21",
		Website:
			"https://www.findaphd.com/phds/project/3-year-phd-position-in-the-thermodynamics-and-rheology-of-polymers-in-solution-at-rwth-aachen-university/?p134042",
	},
	{
		"S.No": "8",
		"Nature of job": "Funded PhD",
		Name: "Artificial Intelligent Hybrid Wireless Networks in IoT",
		University: "University College Dublin",
		Country: "Dublin, Ireland",
		"Application End Date": "Till position filled",
		Website:
			"https://www.findaphd.com/phds/project/engineering-phd-in-university-college-dublin-artificial-intelligent-hybrid-wireless-networks-in-iot/?p128682",
	},
	{
		"S.No": "9",
		"Nature of job": "Funded PhD",
		Name: "Optimisation of Extreme High Speed Laser (EHLA) Coatings.",
		University: "Sheffield Hallam University",
		Country: "Sheffield, England",
		"Application End Date": "9/17/21",
		Website:
			"https://www.findaphd.com/phds/project/optimisation-of-extreme-high-speed-laser-ehla-coatings/?p133437",
	},
	{
		"S.No": "10",
		"Nature of job": "Funded PhD",
		Name: "Surface roughness - a help or a hindrance?",
		University: "Coventry University",
		Country: "Coventryt England",
		"Application End Date": "20 septembert 2021",
		Website: "https://www.findaphd.com/phds/project/surface-roughness-a-help-or-a-hindrance/?p132887",
	},
	{
		"S.No": "11",
		"Nature of job": "Funded PhD",
		Name: "Early non-invasive detection of coronary microvascular disease using AI-based multiparameter analysis and computational simulation",
		University: "Coventry University",
		Country: "Coventryt England",
		"Application End Date": "9/9/21",
		Website:
			"https://www.findaphd.com/phds/project/early-non-invasive-detection-of-coronary-microvascular-disease-using-ai-based-multiparameter-analysis-and-computational-simulation/?p134016",
	},
	{
		"S.No": "12",
		"Nature of job": "Funded PhD",
		Name: "Earth, wind and fire: the effects of vegetation structures on the dynamics of wildfires",
		University: "University of Edinburgh",
		Country: "Edinburgh, Scotland",
		"Application End Date": "9/3/21",
		Website:
			"https://www.findaphd.com/phds/project/earth-wind-and-fire-the-effects-of-vegetation-structures-on-the-dynamics-of-wildfires/?p130562",
	},
	{
		"S.No": "13",
		"Nature of job": "Funded PhD",
		Name: "FIERCE: Fast IntERactive simulation for Crowds and Environments-G",
		University: "University of Leeds",
		Country: "Leeds, England",
		"Application End Date": "Till position filled",
		Website:
			"https://www.findaphd.com/phds/project/fierce-fast-interactive-simulation-for-crowds-and-environments-g/?p129995",
	},
	{
		"S.No": "14",
		"Nature of job": "Funded PhD",
		Name: "Hydrogen Ventilation in a Geological Disposal Facility",
		University: "University of Bristol",
		Country: "Bristol, England",
		"Application End Date": "8/25/21",
		Website:
			"https://www.findaphd.com/phds/project/hydrogen-ventilation-in-a-geological-disposal-facility/?p1308311",
	},
	{
		"S.No": "15",
		"Nature of job": "Funded PhD",
		Name: "Building-resolved large-eddy simulations of wind and dispersion over a city scale urban area",
		University: "University of Southampton",
		Country: "Southampton, England",
		"Application End Date": "8/31/21",
		Website:
			"https://www.findaphd.com/phds/project/building-resolved-large-eddy-simulations-of-wind-and-dispersion-over-a-city-scale-urban-area/?p128716",
	},
	{
		"S.No": "16",
		"Nature of job": "Funded PhD",
		Name: "Structural Modelling and Health Monitoring of Composite and Complex Structures and Systems",
		University: "KU Leuven",
		Country: "Leuven, Belgium",
		"Application End Date": "Till position filled",
		Website:
			"https://www.findaphd.com/phds/project/phd-in-structural-modelling-and-health-monitoring-of-composite-and-complex-structures-and-systems/?p134082",
	},
	{
		"S.No": "17",
		"Nature of job": "Funded PhD",
		Name: "Additive Manufacturing Processing and Shape Memory Effect Characterisation of Nitinol",
		University: "Waterford Institute of Technology",
		Country: "Waterford, Ireland",
		"Application End Date": "9/15/21",
		Website:
			"https://www.findaphd.com/phds/project/additive-manufacturing-processing-and-shape-memory-effect-characterisation-of-nitinol-ref-no-wd-2020-72-wsch/?p134076",
	},
	{
		"S.No": "18",
		"Nature of job": "Funded PhD",
		Name: "Masticatory Robot/Chewing Machine",
		University: "London South Bank University",
		Country: "London, England",
		"Application End Date": "Till position filled",
		Website: "https://www.findaphd.com/phds/program/phd-scholarship-masticatory-robot-chewing-machine/?i152p5395",
	},
	{
		"S.No": "19",
		"Nature of job": "Funded PhD",
		Name: "Developing a Novel High Frequency Resonator Rheometer",
		University: "University of Leeds",
		Country: "Leeds, England",
		"Application End Date": "8/27/21",
		Website: "https://www.findaphd.com/phds/project/developing-a-novel-high-frequency-resonator-rheometer/?p130790",
	},
	{
		"S.No": "20",
		"Nature of job": "Funded PhD",
		Name: "PhD in ocean energy research",
		University: "Maynooth University",
		Country: "Maynooth, Ireland",
		"Application End Date": "till position filled",
		Website:
			"https://www.findaphd.com/phds/project/phd-position-4-year-studentship-eur18-5k-tax-free-p-a-and-fees/?p133844",
	},
	{
		"S.No": "21",
		"Nature of job": "Funded PhD",
		Name: "PhD Studentship in Spine Biomechanics",
		University: "Imperial College London",
		Country: "London, England",
		"Application End Date": "9/3/21",
		Website: "https://www.findaphd.com/phds/project/phd-studentship-in-spine-biomechanics/?p133836",
	},
	{
		"S.No": "22",
		"Nature of job": "Funded PhD",
		Name: "PhD Position in ‘The Chinese state-led development of AI technologies’",
		University: "Copenhagen Business School",
		Country: "Frederiksberg, Denmark",
		"Application End Date": "September 1, 2021",
		Website:
			"https://academicpositions.com/ad/copenhagen-business-school/2021/re-announcement-phd-position-in-the-chinese-state-led-development-of-ai-technologies/161793",
	},
	{
		"S.No": "23",
		"Nature of job": "Funded PhD",
		Name: "A transferable and AI-enabled software security framework",
		University: "University of the West of England",
		Country: "Bristol, England",
		"Application End Date": "10/14/21",
		Website:
			"https://www.findaphd.com/phds/project/a-transferable-and-ai-enabled-software-security-framework/?p134251",
	},
	{
		"S.No": "24",
		"Nature of job": "Funded PhD",
		Name: "Fatigue life assessment methods under fully-reversed cyclic loading (R ratio=-1) and their application in aerospace composite structures",
		University: "University of the West of England",
		Country: "Bristol, England",
		"Application End Date": "10/14/21",
		Website:
			"https://www.findaphd.com/phds/project/fatigue-life-assessment-methods-under-fully-reversed-cyclic-loading-r-ratio-1-and-their-application-in-aerospace-composite-structures/?p134249",
	},
	{
		"S.No": "25",
		"Nature of job": "Funded PhD",
		Name: "Cyber security analytics in telecommunications systems: Managing security and service in complex real-time 5G networks",
		University: "University of the West of England",
		Country: "Bristol, England",
		"Application End Date": "10/14/21",
		Website:
			"https://www.findaphd.com/phds/project/cyber-security-analytics-in-telecommunications-systems-managing-security-and-service-in-complex-real-time-5g-networks/?p134247",
	},
	{
		"S.No": "26",
		"Nature of job": "Funded PhD",
		Name: "Configuration and algorithms for physiological and mental healthcare monitoring systems with wearable sensors",
		University: "University of the West of England",
		Country: "Bristol, England",
		"Application End Date": "10/14/21",
		Website:
			"https://www.findaphd.com/phds/project/configuration-and-algorithms-for-physiological-and-mental-healthcare-monitoring-systems-with-wearable-sensors/?p134245",
	},
	{
		"S.No": "27",
		"Nature of job": "Funded PhD",
		Name: "Optimal control of aquaponic farms for food production using Internet of Things (IoT) and Artificial Intelligence (AI)",
		University: "University of the West of England",
		Country: "Bristol, England",
		"Application End Date": "10/14/21",
		Website:
			"https://www.findaphd.com/phds/project/optimal-control-of-aquaponic-farms-for-food-production-using-internet-of-things-iot-and-artificial-intelligence-ai/?p134244",
	},
	{
		"S.No": "28",
		"Nature of job": "Funded PhD",
		Name: "Detecting ice sheet dynamical imbalance using satellite and meteorological records",
		University: "University of leeds",
		Country: "leeds, England",
		"Application End Date": "8/31/21",
		Website:
			"https://www.findaphd.com/phds/project/detecting-ice-sheet-dynamical-imbalance-using-satellite-and-meteorological-records/?p134240",
	},
	{
		"S.No": "29",
		"Nature of job": "Funded PhD",
		Name: "Exploring Arctic sea ice variability using satellite and meteorological records",
		University: "University of leeds",
		Country: "leeds, England",
		"Application End Date": "8/31/21",
		Website:
			"https://www.findaphd.com/phds/project/exploring-arctic-sea-ice-variability-using-satellite-and-meteorological-records/?p125236",
	},
	{
		"S.No": "30",
		"Nature of job": "Funded PhD",
		Name: "PhD Degrees in the Department of Architecture & Civil Engineering",
		University: "University of Bath",
		Country: "bath, England",
		"Application End Date": "Till positioned filled",
		Website:
			"https://www.findaphd.com/phds/programme/phd-degrees-in-the-department-of-architecture-and-civil-engineering/?p258",
	},
	{
		"S.No": "31",
		"Nature of job": "Funded PhD",
		Name: "Damage sensing underwater soft actuators",
		University: "TalTech – Tallinn University of Technology",
		Country: "Tallin, Estonia",
		"Application End Date": "9/9/21",
		Website: "https://www.findaphd.com/phds/project/damage-sensing-underwater-soft-actuators/?p121411",
	},
	{
		"S.No": "32",
		"Nature of job": "Funded PhD",
		Name: "Design and control of magnetic soft robot for surgical applications",
		University: "University of Leeds",
		Country: "Leeds, England",
		"Application End Date": "9/15/21",
		Website:
			"https://www.findaphd.com/phds/project/design-and-control-of-magnetic-soft-robot-for-surgical-applications/?p129615",
	},
	{
		"S.No": "33",
		"Nature of job": "Funded PhD",
		Name: "Model-based Security Testing for RFIDs in Automotive",
		University: "Coventry University",
		Country: "Coventryt England",
		"Application End Date": "9/30/21",
		Website: "https://www.findaphd.com/phds/project/model-based-security-testing-for-rfids-in-automotive/?p134228",
	},
	{
		"S.No": "34",
		"Nature of job": "Funded PhD",
		Name: "Electric Vehicle Powertrain and Chassis Control System Optimisation",
		University: "Cranfield University",
		Country: "Coventryt England",
		"Application End Date": "9/10/21",
		Website:
			"https://www.findaphd.com/phds/project/electric-vehicle-powertrain-and-chassis-control-system-optimisation/?p134227",
	},
	{
		"S.No": "35",
		"Nature of job": "Post Doc",
		Name: "Postdoctoral Research Fellow position (3 years)",
		University: "University of Bergen",
		Country: "Bergen, Norway",
		"Application End Date": "9/15/21",
		Website:
			"https://academicpositions.com/ad/university-of-bergen/2021/postdoctoral-research-fellow-position-3-years/162348",
	},
	{
		"S.No": "36",
		"Nature of job": "Post Doc",
		Name: "Postdoctoral Fellow in Computational Engineering/ Experimental hemodynamics",
		University: "UNIVERSITY OF STAVANGER",
		Country: "Stavanger, Norway ",
		"Application End Date": "August 20, 2021",
		Website:
			"https://academicpositions.com/ad/university-of-stavanger/2021/postdoctoral-fellow-in-computational-engineering-experimental-hemodynamics/160724",
	},
	{
		"S.No": "37",
		"Nature of job": "Post Doc",
		Name: "2-year postdoc/software engineer position on accelerating the atmospheric chemistry transport model ICON-ART for next-generation supercomputer architectures",
		University: "Empa",
		Country: "Dübendorf, Switzerland",
		"Application End Date": "Unspecified",
		Website:
			"https://academicpositions.com/ad/empa/2021/2-year-postdoc-software-engineer-position-on-accelerating-the-atmospheric-chemistry-transport-model-icon-art-for-next-generation-supercomputer-architectures/162541",
	},
	{
		"S.No": "38",
		"Nature of job": "Post Doc",
		Name: "Postdoc position in Computer Vision and Machine Learning",
		University: "UNIVERSITY OF MALTA",
		Country: "MSD, Malta",
		"Application End Date": "8/31/21",
		Website:
			"https://academicpositions.com/ad/university-of-malta/2021/postdoc-position-in-computer-vision-and-machine-learning/162565",
	},
	{
		"S.No": "39",
		"Nature of job": "Post Doc",
		Name: "Post-doctoral researcher Interoperability of information systems and databases",
		University: "HASSELT UNIVERSITY",
		Country: "Hasselt, Belgium",
		"Application End Date": "8/31/21",
		Website:
			"https://academicpositions.com/ad/hasselt-university/2021/post-doctoral-researcher-interoperability-of-information-systems-and-databases/162506",
	},
	{
		"S.No": "40",
		"Nature of job": "Post Doc+ PHD",
		Name: "one Postdoc and 2 PhD positions in Metamorphic Networking Software / Mobile Code for Trustworthy Computing",
		University: "University of Basel",
		Country: "Basel, Switzerland",
		"Application End Date": "8/29/21",
		Website:
			"https://academicpositions.com/ad/university-of-basel/2021/one-postdoc-and-2-phd-positions-in-metamorphic-networking-software-mobile-code-for-trustworthy-computing/162435",
	},
	{
		"S.No": "41",
		"Nature of job": "Funded PHD",
		Name: "PhD Student Position In The Field Of Optimization And Machine Learning (Prof. A. Lucchi)",
		University: "University of Basel",
		Country: "Basel, Switzerland",
		"Application End Date": "9/4/21",
		Website:
			"https://academicpositions.com/ad/university-of-basel/2021/phd-student-position-in-the-field-of-optimization-and-machine-learning-prof-a-lucchi/162436",
	},
	{
		"S.No": "42",
		"Nature of job": "Post Doc",
		Name: "Post-doctoral Position in High Performance Computing (HPC)",
		University: "UNIVERSITY OF LUXEMBOURG",
		Country: "Luxembourg, Luxembourg",
		"Application End Date": "Unspecified",
		Website:
			"https://academicpositions.com/ad/university-of-luxembourg/2021/post-doctoral-position-in-high-performance-computing-hpc/162457",
	},
	{
		"S.No": "43",
		"Nature of job": "Post Doc",
		Name: "Postdoctoral Researcher In Mixed-Signal Integrated Circuit Design For Edge AI Accelerators",
		University: "Aalto University",
		Country: "Lämpömiehenkuja 2, 02150 Espoo",
		"Application End Date": "September 13, 2021",
		Website:
			"https://academicpositions.com/ad/aalto-university/2021/postdoctoral-researcher-in-mixed-signal-integrated-circuit-design-for-edge-ai-accelerators/162411",
	},
	{
		"S.No": "44",
		"Nature of job": "Post Doc",
		Name: "Research Associate (Postdoc) in SDN and NFV as key enablers for SatCom integration into 5G ecosystem",
		University: "UNIVERSITY OF LUXEMBOURG",
		Country: "Luxembourg, Luxembourg",
		"Application End Date": "Unspecified",
		Website:
			"https://academicpositions.com/ad/university-of-luxembourg/2021/research-associate-postdoc-in-sdn-and-nfv-as-key-enablers-for-satcom-integration-into-5g-ecosystem/162388",
	},
	{
		"S.No": "45",
		"Nature of job": "Funded PhD Project",
		Name: "Electrochemical upgrading of small waste molecules , Chemistry",
		University: "University of Waterloo",
		Country: "Ontario, Canada",
		"Application End Date": "Applications accepted all year round",
		Website:
			"https://www.findaphd.com/phds/project/phd-vacancy-electrochemical-upgrading-of-small-waste-molecules/?p133724",
	},
	{
		"S.No": "46",
		"Nature of job": "Funded PhD Project",
		Name: "Efficient Database Query Processing on Modern Hardware, computer science",
		University: "University of New Brunswick",
		Country: "Canada",
		"Application End Date": "Applications accepted all year round",
		Website:
			"https://www.findaphd.com/phds/project/efficient-database-query-processing-on-modern-hardware/?p131744",
	},
	{
		"S.No": "47",
		"Nature of job": "Funded PhD Project",
		Name: "PHD position in Cybernetic Systems and Control, Mechanical and Aerospace Engineering",
		University: "Arizona State University",
		Country: "Tempe, AZ, USA",
		"Application End Date": "Applications accepted all year round",
		Website: "https://www.findaphd.com/phds/project/phd-position-in-cybernetic-systems-and-control/?p132128",
	},
];