import {
	deborah,
	deepak,
	garrelt,
	garreltAix,
	gaurav,
	gerald,
	ina,
	ivan,
	jenny,
	jules,
	katrin,
	kavita,
	kumar,
	leyva,
	ma,
	mahesh,
	mikhail,
	narain,
	nath,
	oleg,
	omer,
	pattnaik,
	paul,
	rajeev,
	ram,
	ramesh,
	sajida,
	shripad,
	tharmalingam,
	vatsala,
} from "../../../assets";
export const data = [
	{
		name: "Prof. Asit K. Pattnaik",
		designation: "Professor",
		institute: "School of Veterinary and Biomedical Sciences University of Nebraska-Lincoln, USA",
		title: "Foreign Faculty expert under the GIAN program (2018)",
		host: "(Host: Dr. Debashis Nayak and Dr. Sharad Gupta, BSBE)",
		img: pattnaik,
	},
	{
		name: "Prof. Rajeev Ahuja",
		designation: "Professor",
		institute: "Department of Physics & Astronomy, Uppsala University, Sweden",
		title: "Foreign Faculty expert under the GIAN program (2018)",
		host: "(Host: Dr. Biswarup Pathak, Chemistry)",
		img: rajeev,
	},
	{
		name: "Dr. Deborah Sutton",
		designation: "Senior Lecturer in Modern South Asian History,",
		institute: "Lancaster University, UK",
		title: "Foreign Faculty expert under the SPARC program (2018)",
		host: "(Host: Dr. Nirmala Menon, HSS)",
		img: deborah,
	},
	{
		name: "Dr. Ramesh Bhat",
		designation: "Senior Research Fellow",
		institute:
			"School of Veterinary and International Centre for Radio Astronomy Research (ICRAR), Curtin University",
		title: "Foreign Faculty expert (2019)",
		host: "(Host: Dr. Manoneeta Chakraborty, DAASE)",
		img: ramesh,
	},
	{
		name: "Prof Oleg Smirnov",
		designation: "Professor",
		institute: "Radio Astronomy Techniques and Technologies, Rhodes University, South Africa",
		title: "Foreign Faculty expert under the SPARC program (2020)",
		host: "(Host: Dr. Suman Majumdar and Dr. Abhirup Datta, DAASE)",
		img: oleg,
	},
	{
		name: "Prof. Garrelt Mellema",
		designation: "Professor",
		institute: "Stockholm University, Sweden",
		title: "Foreign Faculty expert under the SPARC program (2020)",
		host: "(Host: Dr Suman Majumdar and Dr. Abhirup Datta, DAASE)",
		img: garrelt,
	},
	{
		name: "Dr. Kavita Shah",
		designation: "Professor",
		institute: "Bioorganic Chemistry and Chemical Biology, Purdue University, West Lafayette, USA",
		title: "Foreign Faculty expert under the GIAN Course (2019)",
		host: "(Host: Dr. Prashant Kodgire and Dr. Venkatesh, BSBE)",
		img: kavita,
	},
	{
		name: "Prof. Deepak Kalaskar",
		designation: "Professor",
		institute: "University College London, UK",
		title: "Foreign Faculty expert under UKIERI bilateral project (2019)",
		host: "(Host: Dr. Apurba K. Das, Chemistry)",
		img: deepak,
	},
	{
		name: "Prof. Ram Mohan",
		designation: "Professor",
		institute: "Illinois Wesleyan University, Bloomington, USA",
		title: "Visiting Adjunct Faculty, Chemistry Department",
		host: "(Host: Dr. Venkatesh Chelvam, Chemistry)",
		img: ram,
	},
	{
		name: "Dr. Gerald Dräger",
		designation: "Employee, chemist",
		institute: "Leibniz University, Hannover, Germany",
		title: "International Conference",
		host: "(Host: Dr. Venkatesh Chelvam, Chemistry)",
		img: gerald,
	},
	{
		name: "Prof. Mahesh D. Pandey",
		designation: "Professor",
		institute: "Civil and Environmental Engineering, University of Waterloo, Canada",
		title: "Seminar and Inputs for CE Department MTech Course",
		host: "(Host: Dr. Guru Prakash, CE)",
		img: mahesh,
	},
	{
		name: "Prof. Garrelt Mellema",
		designation: "Professor",
		institute: "Aix-Marseille University",
		title: "Foreign Faculty expert under the SPARC program (2019)",
		host: "(Host: Prof. Sandeep Chaudhary, CE)",
		img: garreltAix,
	},
	{
		name: "Prof. Jenny Southgate",
		designation: "Professor",
		institute: "University of York, UK",
		title: "Collaborative research Assignment (2020)",
		host: "(Host: Dr. Aruna Tiwari, CSE)",
		img: jenny,
	},
	{
		name: "Prof. Katrin Franke",
		designation: "Professor",
		institute: "Norwegian University of Science and Technology, Norway",
		title: "Foreign Faculty expert under the SPARC program (2019)",
		host: "(Host: Dr. Neminath Hubballi, CSE)",
		img: katrin,
	},
	{
		name: "Prof. Gaurav Sharma",
		designation: "Professor",
		institute: "University of Rochester, USA",
		title: "Foreign Faculty expert under the GIAN program (2018)",
		host: "(Host: Dr. Surya Prakash, CSE)",
		img: gaurav,
	},
	{
		name: "Prof. Jules M. Moualeu",
		designation: "Professor",
		institute: "University of the Witwatersrand, Johannesburg, South Africa",
		title: "Foreign Faculty BRICS (2019)",
		host: "(Host: Dr. Dr. Prabhat K. Upadhyay, EE)",
		img: jules,
	},
	{
		name: "Prof. Omer Nour",
		designation: "Professor",
		institute: "Linkoping University, Sweden",
		title: "Foreign Faculty expert under ASEM DUO (2020)",
		host: "(Host: Dr. Shaibal Mukherjee, EE)",
		img: omer,
	},
	{
		name: "Prof. Tharmalingam Ratnarajah",
		designation: "Professor",
		institute: "University of Edinburgh, UK",
		title: "Foreign Faculty expert under the SPARC program (2020)",
		host: "(Host: Prof. Vimal Bhatia, EE)",
		img: tharmalingam,
	},
	{
		name: "Prof. Ina Ganguli",
		designation: "Professor",
		institute: "University of Massachusetts Amherst USA",
		title: "Foreign Faculty expert under the GIAN Course (2018)",
		host: "(Host: Dr. Ruchi Sharma, HSS)",
		img: ina,
	},
	{
		name: "Prof. Paul Arthur",
		designation: "Professor",
		institute: "University of Western Sydney, Australia",
		title: "Foreign Faculty expert under GIAN Course (2016)",
		host: "(Host: Dr. Dr. Nirmala Menon, HSS)",
		img: paul,
	},
	{
		name: "Prof. Mohammad Sajida",
		designation: "Professor",
		institute: "Department of Mechanical Engineering, Qassim University, Saudi Arabia",
		title: "ICMMSC Conference (2018)",
		host: "(Host: Dr. Santanu Manna, Maths)",
		img: sajida,
	},
	{
		name: "Prof. Kumar Singha",
		designation: "Professor",
		institute: "Miami University, Oxford, USA",
		title: "ICMMSC Conference (2018)",
		host: "(Host: Dr. Santanu Manna, Maths)",
		img: kumar,
	},
	{
		name: "Prof. Ivan Slapnicar",
		designation: "Professor",
		institute: "University of Split, Croatia",
		title: "Foreign Faculty expert under GIAN Course (2016)",
		host: "(Host: Dr. Sk Safique Ahmad, Maths)",
		img: ivan,
	},
	{
		name: "Prof. Aghalaya S. Vatsala",
		designation: "Professor",
		institute: "University of Louisiana, USA",
		title: "Foreign Faculty expert under GIAN Course (2017)",
		host: "(Host: Dr. Antony Vijesh, Maths)",
		img: vatsala,
	},
	{
		name: "Prof. Shripad Revankar",
		designation: "Professor",
		institute: "Purude University, USA",
		title: "Foreign Faculty expert under the OVDF (2019)",
		host: "(Host: Dr. Santosh K. Sahu, ME)",
		img: shripad,
	},
	{
		name: "Dr. Yogeshwar Nath Mishra",
		designation: "Researcher at NASA Jet Propulsion Laboratory",
		institute: "Friedrich-Alexander University Erlangen-Nuremberg, Germany",
		title: "Foreign Faculty expert under the SPARC program (2019)",
		host: "(Host: Dr. Devendra Laxmanrao Deshmukh, ME)",
		img: nath,
	},
	{
		name: "Prof. Amitabh Narain",
		designation: "Professor",
		institute: "Michigan Technological University USA",
		title: "Foreign Faculty expert under the VAJRA program (2019)",
		host: "(Host: Dr. Dr. Ritunesh Kumar, ME)",
		img: narain,
	},
	{
		name: "Prof. Y. R. Ma",
		designation: "Professor",
		institute: "NDHU Taiwan, Taiwan",
		title: "Foreign Faculty expert under GIAN Course (2019)",
		host: "(Host: Dr. Rupesh S. Devan & Dr. Parasharam M. Shirage, MEMS)",
		img: ma,
	},
	{
		name: "Prof. Mikhail Ivanchenko",
		designation: "Professor",
		institute: "Lobachevsky State University of Nizhni Novgorod, Russia",
		title: "Foreign Faculty expert under GIAN Course (2017)",
		host: "(Host: Dr. Sarika Jalan, Physics)",
		img: mikhail,
	},
	{
		name: "Prof. Inmaculada Leyva",
		designation: "Professor",
		institute: "Rey Juan Carlos University Spain, Spain",
		title: "Foreign Faculty expert under GIAN Course (2018)",
		host: "(Host: Dr. Sarika Jalan, Physics)",
		img: leyva,
	},
];
