import {
	chem_talks_news,
	ai,
	chemR,
	phyR,
	NSDImg,
	FrenchConsultImg,
	BUL,
	NIDB,
	MoU,
	virtualBooth,
	uoa,
} from "../../../../../assets";

export const data = [
	{
		title: "IIT Indore is participating in the PAN IIT Global Virtual Technology Summit PI-WOT 2021",
		image: virtualBooth,
		desc: "This summit is aimed to showcase the excellence of each IIT in academics, research, and innovations, and reaching out to the IIT Alumni, Industries, and Investors. We are also going to set up one virtual booth representing IIT Indore.\nThe IIT Exhibition Area is now open to receive visitors and will continue during the Summit (17th and 18th September) and close on 18th September when the Summit concludes.You can visit all the IIT Exhibition Area at any time ( 24*7 it is open) of your convenience. You may invite your colleague and friends to join the Summit and also visit the IIT Exhibition Area by sharing the following link with them to register for this event: https://piwot.paniit.org/register-now.php . Participation is open to all.",
		date: "Sep 13, 2021",
		name: "global-virtual-technology-summit",
	},
	{
		title: "Ms. Shalini Singh, Ph.D. Scholar, Dept. of Mechanical Engineering, IIT Indore has received the OVDF fellowship to pursue her research  studies in the University of Alberta.",
		image: uoa,
		desc: "Title of the Research work: “Customized Shape Memory Alloy (SMA) Structures using Plasma and Wire Arc Additive Manufacturing”\nMentoring Faculty from Canada: Prof. Ahmed Qureshi, Associate Professor, Faculty of Engineering, Mechanical Engineering Deptt., University of Alberta, Canada\nMentoring Faculty from IIT Indore: Dr. I. A. Palani, Department of Mechanical Engineering\nDuration:1 year (Jan. 2022-Jan. 2023)",
		date: "Sep 3, 2021",
		name: "shalini",
	},
	{
		image: BUL,
		title: "Forecasting crude oil futures prices by Prof. Date",
		desc: "Dr. Paresh Date, Reader and Director of Research in Mathematics, Brunel University, London, UK has given talk on “Forecasting crude oil futures prices using the Kalman filter and news sentiment” on August 27, 2021 under IAO International Outreach event of IIT Indore. The talk was coordinated by Dr. Abhinoy K. Singh, Department of Electrical Engineering, IIT Indore.",
		link: "https://www.brunel.ac.uk/people/paresh-date",
		name: "crudeOil",
	},
	{
		image: NIDB,
		title: "National Institute of Design Bhopal visited IIT Indore",
		desc: "Officials from National Institute of Design, Bhopal visited International Affairs & Outreach office, IIT Indore on August 23, 2021. During the visit, we had a constructive discussion with NID team to extend our support to establish international office at NID Bhopal. ",
		name: "nidBhopal",
	},
	{
		image: FrenchConsultImg,
		title: "French Consulate General in Mumbai visited IIT Indore",
		desc: "Mrs. Sonia Barbry, French Consulate General in Mumbai and Mr. Thomas Simoes, Director, Alliance Francaise, Bhopal visited IIT Indore on March 18, 2021, and had fruitful discussions on escalating and strengthening the bilateral research work, exchange of students and faculties and many more aspects. ",
		name: "frenchConsulate",
	},
	{
		image: NSDImg,
		title: "IIT Indore celebrated National Science Day in virtual mode",
		desc: "IIT Indore is celebrating the National Science Day on Feb. 28, 2021, where several activities such as daily life physics experiments, chemical illusion, journey through cosmos, mathematical magic, biology talk, will be organized for school kids in virtual mode.",
		link: "https://www.freepressjournal.in/indore/indore-iit-indore-to-celebrate-national-science-day-in-virtual-mode",
		name: "nsd",
	},
	{
		image: MoU,
		title: "MoU signed with University of Alberta, Canada",
		desc: "IIT Indore and University of Alberta, Canada has signed an MOU to escalate the research activities and exchange on the mutually agreeable domains, covering the exchange of students, faculties and staffs, development of joint curriculum, organising joint workshops and conferences, and also to explore the possibilities of joint degree programmes. This MOU has been signed in 2021 and will remain valid for 5 years.",
		link: "https://clt1249866.bmeurl.co/C8589D3",
		name: "mouCanada",
	},
	{
		image: chemR,
		title: "Direct H2O2 synthesis",
		desc: "Catalysis group, IIT Indore and KIT Germany reported their work on shape-selective Pd3Pb nanocrystals based catalysts for direct H2O2 synthesis. Their findings inferred the tuning in electronic structure and lack of Pd ensembles retarted O-O cleavage.",
		link: "https://pubs.acs.org/doi/abs/10.1021/acscatal.0c03561",
		name: "h2o2",
	},
	{
		image: phyR,
		title: "Origin of natural and magnetic field induced polar order",
		desc: "The group of Dr. Sagdeo, IIT Indore and STFC Rutherford Appleton Laboratory, UK have reported the possible origin of natural and magnetic field induced switchable polar order near room temperature (RT) in PrFe1/2Cr1/2O3",
		link: "https://journals.aps.org/prb/abstract/10.1103/PhysRevB.104.035101",
		name: "magneticField",
	},
	{
		title: "Impact of the Digital Revolution on Higher Education",
		image: ai,
		desc: 'Dr. Aruna Tiwari, Associate Professor, CSE represented IIT Indore as an Artificial Intelligence expert in the Internationalist Podcast series on  "Impact of the digital revolution on higher education", organized by the Association of Commonwealth Universities, UK on June 8, 2021.',
		// date: "June 8, 2021",
		name: "digitalRevolution",
	},
	{
		title: "Chemistry Talks",
		image: chem_talks_news,
		desc: " Chemistry Talks: India celebrates the National Science Day on 28th February to mark the discovery of the Raman effect by Sir C. V. Raman On this occasion, the Department of Chemistry ,Indian Institute of Technology Indore is organizing Chemistry Talks.In the month of February, chemistry-based research talks from several eminent speakers across the world have been scheduled.\nChemistry Lectures aim to provide a platform for eminent chemists from all over the world to share and discuss wider aspects of the domain of chemical sciences and allied areas. The webinar is expected to provide a unique opportunity to establish new and ever-lasting bonding between the researchers, and inspire the young students to explore new ways to understand chemistry and its interface.",
		// date: "January 28, 2021",
		name: "chemTalks",
	},
];
