import React, { useState } from "react";
import { MHRDPage } from "./MHRDPage";
import { sahu, iitkgp } from "../../../../assets";

export const Gian = () => {
	const [info] = useState([
		{
			"S. No.": 1,
			Year: "2020",
			Title: "Two Phase Flows in a Micro and Milli Channels: Theoretical Backgrounds and Numerical Proofs",
			Ip: "Dr. Ritunesh Kumar",
			Fp: "Dr. Abive Rufat",
			Fu: "St. Petersburg State Institute of Technology",
			Country: "Russia",
			Duration: "10-03-2020 to 19-03-2020",
		},
		{
			"S. No.": 2,
			Year: "2020",
			Title: "Use of Hydrogen as a Future Fuel",
			Ip: "Dr. Shanmugam Dhinakaran",
			Fp: "Dr. Weeratunge Malalasekera",
			Fu: "Loughborough University",
			Country: "UK",
			Duration: "06-04-2020 to 10-04-2020",
		},
		{
			"S. No.": 3,
			Year: "2020",
			Title: 'Principles of Ligand - Targeted Drug Delivery: Design and Development of "Smart Drugs"',
			Ip: "Dr. Venkatesh Chelvam",
			Fp: "Dr. Shrinivasarao Madduri",
			Fu: "Purdue University",
			Country: "USA",
			Duration: "05-05-2020 to 16-05-2020",
		},
		{
			"S. No.": 1,
			Year: "2019",
			Title: "One Dimensional Metal-Oxide Nanostructures: Recent Developments in Synthesis, Characteristics and Applications",
			Ip: "Dr. Parasharam M. Shirage & Dr. Rupesh S. Devan",
			Fp: "Prof. Yuan-Ron Ma",
			Fu: "National Dong Hwa University",
			Country: "Taiwan",
			Duration: "01-04-2019 to 10-04-2019",
		},
		{
			"S. No.": 2,
			Year: "2019",
			Title: "Principles of Drug Discovery, Design and Development: Modern Concepts and Applications",
			Ip: "Dr. Chelvam Venkatesh",
			Fp: "Prof. Apurba Dutta",
			Fu: "University of Kansas",
			Country: "USA",
			Duration: "27-05-2019 to 07-06-2019",
		},
		{
			"S. No.": 3,
			Year: "2019",
			Title: "GPU Computing in Computational Biology",
			Ip: "Dr. Parimal Kar",
			Fp: "Prof. Siegfried Hoefinger",
			Fu: "Vienna University of Technology",
			Country: "Austria",
			Duration: "15-07-2019 to 19-07-2019",
		},
		{
			"S. No.": 4,
			Year: "2019",
			Title: "Lattice Boltzmann Methods for Multi-Phase and Multi-Component flows",
			Ip: "Dr. Shanmugam Dhinakaran",
			Fp: "Prof. Abdulmajeed Mohamad",
			Fu: "University of Calgary",
			Country: "Canada",
			Duration: "05-08-2019 to 16-08-2019",
		},
		{
			"S. No.": 5,
			Year: "2019",
			Title: "Ultra Clean and Low Pulsation Gas Turbines",
			Ip: "Dr. Devendra L. Deshmukh",
			Fp: "Prof. Christian Oliver Paschereit",
			Fu: "TU Berlin",
			Country: "Germany",
			Duration: "03-11-2019 to 07-11-2019",
		},
		{
			"S. No.": 6,
			Year: "2019",
			Title: "Advance combustion modelling with computational fluid mechanics",
			Ip: "Dr. Shanmugam Dhinakaran",
			Fp: "Prof. Weeratunge Malalasekera",
			Fu: "Loughborough University",
			Country: "UK",
			Duration: "08-4-19 to 12-04-19",
		},
		{
			"S. No.": 1,
			Year: "2018",
			Title: "Grid Integration of Pv Solar and Wind Power Systems",
			Ip: "Dr. Trapti Jain",
			Fp: "Prof.  Rajiv K. Varma",
			Fu: "The University of Western Ontario",
			Country: "Canada",
			Duration: "12-02-2018 to 16-02-2018",
		},
		{
			"S. No.": 2,
			Year: "2018",
			Title: "Reliability Engineering and Asset Management",
			Ip: "Dr. Bhupesh Kumar Lad",
			Fp: "Prof.  Ajith Kumar Parlikad",
			Fu: "Cambridge University",
			Country: "UK",
			Duration: "19-03-2018 to 23-03-2018",
		},
		{
			"S. No.": 3,
			Year: "2018",
			Title: "Biological Treatment of Metals and Metalloids Laden Wastewater: Microbiology, Process Technology and Resource Recovery",
			Ip: "Dr. Kiran Bala",
			Fp: "Prof.  Eric Van Hullebusch",
			Fu: "Université de Paris",
			Country: "Holland, Europe",
			Duration: "12-03-2018 to 17-03-2018",
		},
		{
			"S. No.": 4,
			Year: "2018",
			Title: "Computationally Aided Materials Designing for Materials Genome",
			Ip: "Dr. Biswarup Pathak",
			Fp: "Prof.  Rajeev Ahuja",
			Fu: "Uppsala University",
			Country: "Sweden",
			Duration: "04-01-2018 to 08-01-2018",
		},
		{
			"S. No.": 5,
			Year: "2018",
			Title: "Economics of Science,Technology and Innovation: Empirical Approaches and Randomized Control Trials(RCTs)",
			Ip: "Dr. Ruchi Sharma",
			Fp: "Prof.  Ina Ganguli",
			Fu: "University of Massachusetts Amherst",
			Country: "USA",
			Duration: "10-01-2018 to 14-01-2018",
		},
		{
			"S. No.": 6,
			Year: "2018",
			Title: "Metal-Ligand Interplay in Advanced Coordination Chemistry",
			Ip: "Professor Pradeep Mathur",
			Fp: "Prof.  Pierre Braunstein",
			Fu: "University of Konstanz",
			Country: "USA",
			Duration: "05-02-2018 to 09-02-2018",
		},
		{
			"S. No.": 7,
			Year: "2018",
			Title: "Media Security and Forensics",
			Ip: "Dr. Surya Prakash",
			Fp: "Prof.  Gaurav Sharma",
			Fu: "University of Rochester",
			Country: "USA",
			Duration: "26-03-2018 to 06-04-2018",
		},
		{
			"S. No.": 8,
			Year: "2018",
			Title: "Ubiquitous Computing",
			Ip: "Dr. Abhishek Srivastava",
			Fp: "Prof.  Hee Yong Youn",
			Fu: "Sungkyunkwan University",
			Country: "South Korea",
			Duration: "15-01-2018 to 26-01-2018",
		},
		{
			"S. No.": 9,
			Year: "2018",
			Title: "Vaccines for Human and Animal Viral Pathogens",
			Ip: "Dr. Debasis Nayak",
			Fp: "Prof.  Asit K Pattnaik",
			Fu: "University of Nebraska",
			Country: "USA",
			Duration: "02-07-2018 to 07-07-2018",
		},
		{
			"S. No.": 10,
			Year: "2018",
			Title: "Supermolecular Science: Basic Concepts, New Directions and Technology",
			Ip: "Dr. Rajneesh Misra",
			Fp: "Prof.  Francis D’Souza",
			Fu: "University of North Texas",
			Country: "USA",
			Duration: "12-03-2018 to 18-03-2018",
		},
		{
			"S. No.": 11,
			Year: "2018",
			Title: "Advanced Pattern Recognition Techniques for Biometrics",
			Ip: "Dr. Surya Prakash",
			Fp: "Prof.  Massimo Tistarelli",
			Fu: "University of Sassari",
			Country: "Italy",
			Duration: "05-03-2018 to 09-03-2018",
		},
		{
			"S. No.": 12,
			Year: "2018",
			Title: "Fundamentals of Solid State Physics: From Theoretical and Computational Concepts to Recent Applications in Information Technology",
			Ip: "Dr. M. Anbarasu",
			Fp: "Prof.  Riccardo Mazzarello",
			Fu: "RWTH Aachen University",
			Country: "Germany",
			Duration: "05-02-2018 to 16-02-2018",
		},
		{
			"S. No.": 13,
			Year: "2018",
			Title: "Explosive Transitions in Complex Networks: New Opportunities, New Dangers",
			Ip: "Dr. Sarika Jalan",
			Fp: "Prof.  Inmaculada Leyva",
			Fu: "Rey Juan Carlos University",
			Country: "Spain",
			Duration: "15-01-2018 to 19-01-2018",
		},
		{
			"S. No.": 14,
			Year: "2018",
			Title: "Energy, Education and Innovation",
			Ip: "Dr. Shanmugam Dhinakaran",
			Fp: "Prof.  Yunus A Cengel",
			Fu: "University of Nevada",
			Country: "USA",
			Duration: "12-03-2018 to 16-03-2018",
		},
		{
			"S. No.": 15,
			Year: "2018",
			Title: "Inorganic Chemistry of Imaging: Magnetic Resonance and Optical Imaging with Coordination Complexes",
			Ip: "Dr. Mobin Shaikh",
			Fp: "Prof.  Janet R. Morrow",
			Fu: "State University of New York",
			Country: "USA",
			Duration: "08-01-2018 to 12-01-2018",
		},
		{
			"S. No.": 16,
			Year: "2018",
			Title: "Laser Assisted Surface Micro and Nano-Fabrication",
			Ip: "Dr. I.A. Palani",
			Fp: "Prof.  Daisuke Nakamura",
			Fu: "Kyushu University",
			Country: "Japan",
			Duration: "08-07-2018 to 14-07-2018",
		},
		{
			"S. No.": 17,
			Year: "2018",
			Title: "Basic Principles and Applications of Photovoltaic Devices",
			Ip: "Dr. Parasharam M. Shirage",
			Fp: "Prof. Dr. Kim Jin Hyeok",
			Fu: "Chonnam National University",
			Country: "--",
			Duration: "10-12-2018 to 20-12-2018",
		},
		{
			"S. No.": 18,
			Year: "2018",
			Title: "Advance concepts in the Synthesis of Pharmaceutical Drugs",
			Ip: "Dr. Chelvam Venkatesh",
			Fp: "Prof. Ram Mohan",
			Fu: "Illinois Wesleyan University",
			Country: "USA",
			Duration: "14-6-18 to 21-6-18",
		},
		{
			"S. No.": 19,
			Year: "2018",
			Title: "Modern Power Distribution Systems",
			Ip: "Prof. Trapti Jain",
			Fp: "--",
			Fu: "--",
			Country: "--",
			Duration: "08-1-18 to 12-01-18",
		},
		{
			"S. No.": 20,
			Year: "2018",
			Title: "Network Science - From Structure to Dynamics",
			Ip: "Dr. Sarika Jalan",
			Fp: "Prof.  Baruch Barzel",
			Fu: "Bar-Ilan University",
			Country: "Israel",
			Duration: "06-8-18 to 10-8-18",
		},
		{
			"S. No.": 1,
			Year: "2017",
			Title: "Complexity and Dynamics in Neuroscience",
			Ip: "Dr. Sarika Jalan",
			Fp: "Prof. Mikhail Ivanchenko",
			Fu: "Lobachevsky State University of Nizhni Novgorod",
			Country: "Russia",
			Duration: "01-11-2017 to 08-11-2017",
		},
		{
			"S. No.": 2,
			Year: "2017",
			Title: "Introduction to Thermal Systems Design",
			Ip: "Dr. E. Anil Kumar",
			Fp: "Prof. Srinivas Garimella",
			Fu: "College of Engineering Georgia",
			Country: "USA",
			Duration: "11-09-2017 to 15-09-2017",
		},
		{
			"S. No.": 3,
			Year: "2017",
			Title: "Theory and Application of Wavelets and Framelets",
			Ip: "Dr. Niraj Kumar Shukla",
			Fp: "Prof. Bin Han",
			Fu: "University of Alberta Edmonton",
			Country: "Canada",
			Duration: "28-12-2017 to 04-01-2018",
		},
		{
			"S. No.": 4,
			Year: "2017",
			Title: "Quasiconformal Mappings and Their Applications",
			Ip: "Dr. Swadesh Kumar Sahoo",
			Fp: "Prof. Pekka Koskela",
			Fu: "University of Jyväskylä",
			Country: "Finland",
			Duration: "11-12-2017 to 16-12-2017",
		},
		{
			"S. No.": 5,
			Year: "2017",
			Title: "Porous and Granular Materials: Applications in Modern Science and Technology",
			Ip: "Dr. Shanmugam Dhinakaran",
			Fp: "Prof. Arzhang Khalili",
			Fu: "Max Planck Institute for Marine Microbiology Bremen",
			Country: "Germany",
			Duration: "18-12-2017 to 29-12-2017",
		},
		{
			"S. No.": 6,
			Year: "2017",
			Title: "Adsorption Science and Technology for Cooling and Desalination Applications",
			Ip: "Dr. Anil Kumar Emadabathuni",
			Fp: "Prof. Bidyut BaranSaha",
			Fu: "Kyushu University",
			Country: "Japan",
			Duration: "11-09-2017 to 21-09-2017",
		},
		{
			"S. No.": 7,
			Year: "2017",
			Title: "Data Protection – From Principles to Practice",
			Ip: "Dr. Somnath Dey",
			Fp: "Prof. Anwitaman Datta",
			Fu: "Nanyang Technological University",
			Country: "Singapore",
			Duration: "18-12-2017 to 22-12-2017",
		},
		{
			"S. No.": 8,
			Year: "2017",
			Title: "Second Law Analysis of Thermal Energy Storage Systems",
			Ip: "Dr. Anil Kumar Emadabathuni",
			Fp: "Prof. Bale V. Reddy",
			Fu: "University of New Brunswick",
			Country: "Canada",
			Duration: "17-07-2017 to 22-07-2017",
		},
		{
			"S. No.": 9,
			Year: "2017",
			Title: "Advanced Radar System Design and Signal Processing",
			Ip: "Dr. Vimal Bhatia",
			Fp: "Prof. Amit Kumar Mishra",
			Fu: "University of Cape Town",
			Country: "South Africa",
			Duration: "18-12-2017 to 22-12-2017",
		},
		{
			"S. No.": 10,
			Year: "2017",
			Title: "Small Scale Combined Heat and Power Generation Units: Modelling of Thermal-Hydraulic Issues, System Design and Operation",
			Ip: "Dr. Ritunesh Kumar",
			Fp: "Prof. Dariusz Mikielewicz",
			Fu: "Gdansk University of Technology",
			Country: "Poland",
			Duration: "20-11-2017 to 24-11-2017",
		},
		{
			"S. No.": 11,
			Year: "2017",
			Title: "Generalized Iterative Methods for Non-Linear Differential Equations",
			Ip: "Dr. Antony Vijesh",
			Fp: "Prof. Aghalaya S. Vatsala",
			Fu: "University of Louisiana",
			Country: "USA",
			Duration: "18-12-2017 to 22-12-2017",
		},
		{
			"S. No.": 12,
			Year: "2017",
			Title: "Fundamentals and Applications of Absorption Heat Pumps and Refrigeration Systems",
			Ip: "Dr. Subba Reddy Daggumati",
			Fp: "Prof. Alberto Coronas",
			Fu: "Universitat Rovira i Virgili",
			Country: "Spain",
			Duration: "14-12-2017 to 19-12-2017",
		},
		{
			"S. No.": 13,
			Year: "2017",
			Title: "Next Generation Solar Cells in The Realm of Future Energy Challenges: From Materials Design to Device Architectures",
			Ip: "Dr. Vipul Singh",
			Fp: "Prof. Shyam Sudhir Pandey",
			Fu: "Kyushu Institute of Technology",
			Country: "Japan",
			Duration: "11-12-2017 to 16-12-2017",
		},
		{
			"S. No.": 14,
			Year: "2017",
			Title: "How Next Generation Sequencing (Ngs) Untying the Knots in Viral Pathogenesis",
			Ip: "Dr. Hem Chandra Jha",
			Fp: "Prof. Subhash C Verma",
			Fu: "University of Nevada",
			Country: "USA",
			Duration: "15-10-2017 to 22-10-2017",
		},
		{
			"S. No.": 15,
			Year: "2017",
			Title: "New Developments in Global Political Theory: Comparative, Decolonial and Indian Political Theory",
			Ip: "Dr. Bharath Kumar",
			Fp: "Prof. Aakash Singh Rathore",
			Fu: "University of Luiss",
			Country: "Italy",
			Duration: "04-12-2017 to 08-12-2017",
		},
		{
			"S. No.": 16,
			Year: "2017",
			Title: "Kinematics and Design of Parallel Manipulators",
			Ip: "Dr. Santhakumar Mohan",
			Fp: "Prof. Philippe Wenger",
			Fu: "Laboratoire desSciences du Numérique de Nantes",
			Country: "France",
			Duration: "06-12-2017 to 11-12-2017",
		},
		{
			"S. No.": 17,
			Year: "2017",
			Title: "Humanoid Robotics: Modelling and Control",
			Ip: "Dr. Santhakumar Mohan",
			Fp: "Prof. Christine Chevallereau",
			Fu: "Centre national de larecherche scientifique",
			Country: "France",
			Duration: "06-12-2017 to 11-12-2017",
		},
		{
			"S. No.": 18,
			Year: "2017",
			Title: "Multibody Dynamics",
			Ip: "Dr. Santhakumar Mohan",
			Fp: "Prof. Burkhard Corves",
			Fu: "RWTH Aachen University",
			Country: "Germany",
			Duration: "02-10-2017 to 06-10-2017",
		},
		{
			"S. No.": 19,
			Year: "2017",
			Title: "Single Molecule Magnetism",
			Ip: "Professor Pradeep Mathur",
			Fp: "Prof. Richard Layfield",
			Fu: "University of Manchester",
			Country: "UK",
			Duration: "06-08-2017 to 27-10-2017",
		},
		{
			"S. No.": 20,
			Year: "2017",
			Title: "Advances and Opportunities in Passive Micro and Miniature Technologies for Energy and Thermal Systems",
			Ip: "Dr. Shanmugam Dhinakaran",
			Fp: "Prof. Amir Faghri",
			Fu: "University of Connecticut",
			Country: "USA",
			Duration: "09-01-2017 to 13-01-2017",
		},
		{
			"S. No.": 21,
			Year: "2017",
			Title: "Chemistry and Biology of Carbohydrates",
			Ip: "Dr. Chelvam Venkatesh",
			Fp: "Prof. Fabian Pfrengle",
			Fu: "Max Planck Institute of Colloids and Interfaces",
			Country: "Germany",
			Duration: "06-11-2017 to 17-11-2017",
		},
		{
			"S. No.": 1,
			Year: "2016",
			Title: "Chemical Sensors: Principles, Technologies and Applications",
			Ip: "Dr. Parasharam M. Shirage,",
			Fp: "Prof. Giovanni Neri",
			Fu: "University of Messina",
			Country: "Italy",
			Duration: "01-07-2016 to 09-07-2016",
		},
		{
			"S. No.": 2,
			Year: "2016",
			Title: "Network Science and Multi-Agent Systems",
			Ip: "Dr. Sarika Jalan",
			Fp: "Prof. S. Lakshmivarahan",
			Fu: "University of Oklahoma",
			Country: "USA",
			Duration: "30-05-2016 to 10-06-2016",
		},
		{
			"S. No.": 3,
			Year: "2016",
			Title: "Statistics in Systems Biology and Programming",
			Ip: "Dr. Sarika Jalan",
			Fp: "Prof. Oleg Blyuss",
			Fu: "University College London",
			Country: "UK",
			Duration: "22-08-2016 to 27-08-2016",
		},
		{
			"S. No.": 4,
			Year: "2016",
			Title: "Biomathematics: From Gene Expression to Bone Mechanics",
			Ip: "Dr. Sarika Jalan",
			Fp: "Prof. Alexey Zaikin",
			Fu: "University College London",
			Country: "UK",
			Duration: "22-08-2016 to 27-08-2016",
		},
		{
			"S. No.": 5,
			Year: "2016",
			Title: "Basic Concepts andIssues in Big Data Management",
			Ip: "Dr. Gourinath Banda",
			Fp: "Prof. Nicolas Spyratos",
			Fu: "University of Paris-South",
			Country: "France",
			Duration: "05-12-2016 to 17-12-2016",
		},
		{
			"S. No.": 6,
			Year: "2016",
			Title: "Organometallics:Applications in Material Science and Drug Discovery",
			Ip: "Dr. Rajneesh Misra",
			Fp: "Prof. Holger Butenschön",
			Fu: "University of Hannover",
			Country: "Germany",
			Duration: "22-11-2016 to 02-12-2016",
		},
		{
			"S. No.": 7,
			Year: "2016",
			Title: "Big Data Stream Analytics",
			Ip: "Dr. M. Ashok Kumar, Discipline of Mathematics",
			Fp: "Prof. Yann Busnel",
			Fu: "Crest (Ensai) / Inria Rennes",
			Country: "France",
			Duration: "26-10-2016 to 01-11-2016",
		},
		{
			"S. No.": 8,
			Year: "2016",
			Title: "Introduction to Principles of Green Chemistry",
			Ip: "Dr. Chelvam Venkatesh",
			Fp: "Prof. Ram Mohan",
			Fu: "Illinois Wesleyan University Bloomingto",
			Country: "USA",
			Duration: "17-06-2016 to 24-06-2016",
		},
		{
			"S. No.": 9,
			Year: "2016",
			Title: "Modern Photochemistry and Photocatalysis",
			Ip: "Dr. Chelvam Venkatesh",
			Fp: "Prof. Malte Brasholz",
			Fu: "University of Hamburg",
			Country: "Germany",
			Duration: "04-07-2016 to 15-07-2016",
		},
		{
			"S. No.": 10,
			Year: "2016",
			Title: "Introduction to Heat Pipe Science and Technology",
			Ip: "Dr. E. Anil Kumar",
			Fp: "Prof. Ing. habil. Manfred Groll",
			Fu: "University Stuttgart",
			Country: "Germany",
			Duration: "06-12-2016 to 19-12-2016",
		},
		{
			"S. No.": 11,
			Year: "2016",
			Title: "Chemical Biology: The Integration of Chemistry, Biology, and Medicine",
			Ip: "Dr. Chelvam Venkatesh",
			Fp: "Prof. Kavita Shah",
			Fu: "Purdue University, Indiana",
			Country: "USA",
			Duration: "13-06-2016 to 24-06-2016",
		},
		{
			"S. No.": 12,
			Year: "2016",
			Title: "Linear and Nonlinear Systems and Optimization with Applications in Medical Imaging, Optimal Design, and Graphics",
			Ip: "Dr. Kapil Ahuja",
			Fp: "Prof. Eric de Sturler",
			Fu: "University of Illinois",
			Country: "USA",
			Duration: "25-07-2016 to 05-08-2016",
		},
		{
			"S. No.": 13,
			Year: "2016",
			Title: "Catalysis by Metal Complexes",
			Ip: "Professor Pradeep Mathur",
			Fp: "Prof. Pierre H. Dixneuf",
			Fu: "University of Rennes",
			Country: "France",
			Duration: "21-11-2016 to 26-11-2016",
		},
		{
			"S. No.": 14,
			Year: "2016",
			Title: "Neural Networks Learning Theory – Advanced Topics",
			Ip: "Dr. Aruna Tiwari",
			Fp: "Prof. Suresh Sundaram",
			Fu: "Nanyang Technological University",
			Country: "Singapore",
			Duration: "08-08-2016 to 07-08-2016",
		},
		{
			"S. No.": 15,
			Year: "2016",
			Title: "Microreactors: Mathematical Modelling of Hydrodynamics, Heat and Mass Transfer, Design and Fabrication",
			Ip: "Dr. Ritunesh Kumar",
			Fp: "Prof. Rufat Abiev",
			Fu: "St. Petersburg State Institute of Technology (Technical University)",
			Country: "Russia",
			Duration: "01/11/2017 to 10/11/2017",
		},
		{
			"S. No.": 16,
			Year: "2016",
			Title: "Probabilistic Models and Belief Propagation",
			Ip: "Dr. Surya Prakash",
			Fp: "Prof. Gaurav Sharma",
			Fu: "University of Rochester",
			Country: "USA",
			Duration: "01-08-2016 to 10-08-2016",
		},
		{
			"S. No.": 17,
			Year: "2016",
			Title: "High-Pressure Synthesized Materials: A Chest of Treasure and Hints",
			Ip: "Dr. Parasharam M. Shirage",
			Fp: "Prof. Akira IYO",
			Fu: "Institute of Advanced Industrial Science and Technology (AIST)",
			Country: "Japan",
			Duration: "11-07-2016 to 19-07-2016",
		},
		{
			"S. No.": 18,
			Year: "2016",
			Title: "An Advanced Introduction to The Finite Volume Methods in Computational Fluid Dynamics (with Open Foam)",
			Ip: "Dr. Shanmugam Dhinakaran",
			Fp: "Prof. Marwan Darwish",
			Fu: "American University of Beirut",
			Country: "Lebanon",
			Duration: "05-09-2016 to 09-09-2016",
		},
		{
			"S. No.": 19,
			Year: "2016",
			Title: "Digital Humanities: Tools, Texts and Theory",
			Ip: "Dr. Nirmala Menon",
			Fp: "Prof. Paul Arthur",
			Fu: "University of Western Sydney",
			Country: "Australia",
			Duration: "19-03-2016 to 25-03-2016",
		},
		{
			"S. No.": 20,
			Year: "2016",
			Title: "Intellectual Property Rights (IPR) and International Economic Development",
			Ip: "Dr. Ruchi Sharma",
			Fp: "Prof. Walter G. Park",
			Fu: "American University",
			Country: "USA",
			Duration: "12-12-2016 to 16-12-2016",
		},
		{
			"S. No.": 21,
			Year: "2016",
			Title: "Modern Applications of Numerical Linear Algebra Methods",
			Ip: "Dr. Sk Safique Ahmad",
			Fp: "Prof. Ivan Slapnicar",
			Fu: "University of Split",
			Country: "Croatia",
			Duration: "27-06-2016 to 05-07-2016",
		},
		{
			"S. No.": 22,
			Year: "2016",
			Title: "Human Infectious Disease and Animal Models",
			Ip: "Dr. Debasis Nayak",
			Fp: "Prof. Siddappa Byrareddy",
			Fu: "University of Nebraska Medical Center",
			Country: "USA",
			Duration: "01-07-2016 to 09-07-2016",
		},
		{
			"S. No.": 23,
			Year: "2016",
			Title: "Flow, heat and Mass Transfer Through Porous Media and Critical Thermal Issues in 3D chips",
			Ip: "Dr. Shanmugam Dhinakaran",
			Fp: "--",
			Fu: "--",
			Country: "--",
			Duration: "12/12/2016 to 16/12/2016",
		},
		{
			"S. No.": 24,
			Year: "2016",
			Title: "Fundamentals and Applications of The Principles of Optimization to Various Disciplines – Engineering, Business, Life Sciences",
			Ip: "Dr. Sarika Jalan",
			Fp: "Prof. Chandrasekhar Putcha",
			Fu: "California State University",
			Country: "USA",
			Duration: "27-06-2016 to 01-07-2016",
		},
	]);

	const [person] = useState({
		img: sahu,
		name: "Dr. Santosh K. Sahu",
		designation: "Associate Professor, ME",
		email: "gian_iiti@iiti.ac.in",
	});

	const [insti] = useState({
		img: iitkgp,
		name: "Indian Institute of Technology Kharagpur",
		link: "https://gian.iitkgp.ac.in/",
	});

	const [desc] = useState(
		"Govt. of India approved a new program titled Global Initiative of Academic Networks (GIAN) in Higher Education aimed at tapping the talent pool of scientists and entrepreneurs, internationally to encourage their engagement with the institutes of Higher Education in India so as to augment the country's existing academic resources, accelerate the pace of quality reform, and elevate India's scientific and technological capacity to global excellence."
	);

	const [name] = useState("GIAN");

	const [grants] = useState([
		{
			"Name of the Faculty": "Dr. Venkatesh Chelvam",
			Department: "Chemistry",
			"Funding Agency": "Global Initiatives for Academic Networks, MHRD, Govt. of India",
			"Title of the Grant": "Introduction to Principles of Green Chemistry",
			"Foreign Collaborator(s)": "Prof. Ram Mohan, Illinois Wesleyan University, Bloomington, USA",
			Amount: "USD 12,000",
			"Year of Award - Year of Completion": "June. 2016",
		},
		{
			"Name of the Faculty": "Dr. Venkatesh Chelvam",
			Department: "Chemistry",
			"Funding Agency": "Global Initiatives for Academic Networks, MHRD, Govt. of India",
			"Title of the Grant": "Modern Photochemistry and Photocatalysis",
			"Foreign Collaborator(s)": "Prof. Malte Brasholz, University of Rostock, Germany",
			Amount: "USD 12,000",
			"Year of Award - Year of Completion": "July. 2016",
		},
		{
			"Name of the Faculty": "Dr. Venkatesh Chelvam",
			Department: "Chemistry",
			"Funding Agency": "Global Initiatives for Academic Networks, MHRD, Govt. of India",
			"Title of the Grant": "Advanced Concepts in the Synthesis of Pharmaceutical Drugs",
			"Foreign Collaborator(s)": "Prof. Ram Mohan, Illinois Wesleyan University, Bloomington, USA",
			Amount: "USD 8,000",
			"Year of Award - Year of Completion": "June. 2018",
		},
		{
			"Name of the Faculty": "Dr. Venkatesh Chelvam",
			Department: "Chemistry",
			"Funding Agency": "Global Initiatives for Academic Networks, MHRD, Govt. of India",
			"Title of the Grant": "Chemistry and Biology of Carbohydrates",
			"Foreign Collaborator(s)":
				"Prof. Fabian Pfrengle, Max-Planck-Institute of Colloids and Interfaces, Germany ",
			Amount: "USD 12,000",
			"Year of Award - Year of Completion": "November. 2017",
		},
		{
			"Name of the Faculty": "Dr. Venkatesh Chelvam",
			Department: "Chemistry",
			"Funding Agency": "Global Initiatives for Academic Networks, MHRD, Govt. of India",
			"Title of the Grant":
				"Principles of Drug Discovery, Design, and Development: Modern Concepts and Applications",
			"Foreign Collaborator(s)": "Prof. Apurba Dutta, Univeristy of Kansas, USA",
			Amount: "USD 12,000",
			"Year of Award - Year of Completion": "May. 2019",
		},
		{
			"Name of the Faculty": "Dr. Venkatesh Chelvam",
			Department: "Chemistry",
			"Funding Agency": "Global Initiatives for Academic Networks, MHRD, Govt. of India",
			"Title of the Grant":
				"Principles of Ligand-Targeted Drug Delivery: Design and Development of ‘Smart Drugs’",
			"Foreign Collaborator(s)": "Dr. Madduri Sriniasarao, Purdue Univversity, USA",
			Amount: "USD 12,000",
			"Year of Award - Year of Completion": "May. 2020",
		},
		{
			"Name of the Faculty": "Dr. Venkatesh Chelvam",
			Department: "BSBE",
			"Funding Agency": "Department of Biotechnology-British council",
			"Title of the Grant":
				"Diagnosis of Prostate cancer by Prostate Specific Membrane Antigen (PSMA) Targeted Quantum Dots",
			"Foreign Collaborator(s)": "Prof. Paul Roach, Keele University, Staffordshire, UK",
			Amount: "15,00,000/-",
			"Year of Award - Year of Completion": "Feb. 2016-July 2016",
		},
		{
			"Name of the Faculty": "Dr. Venkatesh Chelvam",
			Department: "BSBE",
			"Funding Agency": "Global Initiatives for Academic Networks, MHRD, Govt. of India",
			"Title of the Grant": "Chemical Biology: The Integration of Medicine, Biology and Chemistry ",
			"Foreign Collaborator(s)": "Prof. Kavita Shah, Purdue University, USA",
			Amount: "USD 12,000",
			"Year of Award - Year of Completion": "June. 2016",
		},
	]);

	return <MHRDPage info={info} name={name} desc={desc} insti={insti} person={person} grants={grants} />;
};
