import {
	person,
	Prof_William,
	raghu,
	Professor_David,
	automative,
	ProfRaghu,
	joshi,
	scitech,
	jeevant,
	bishow,
	somak,
	sastry,
	saumitra,
	shor,
	nobel,
	grp3,
	photocat,
	organo,
	nano,
	boron,
	physics,
	ajoy,
	amit,
	amol,
	bm,
	dks,
	mani,
	srubabati,
	sunilGupta,
	tarun,
	yusuf,
	ramanujan,
	spatel,
	ashish,
	avinash,
	harekrishna,
	toneTonjum,
	biswarup,
	ruchi,
	nirmala,
	prashant,
	debasis,
	malte,
	halet,
	holger,
	silke,
	dipak,
	global_health_crisis_iv,
	gagandeep,
	bruce,
	FLYER_Maths_Seminar,
	ashisha,
	manna,
	bibek,
	paresh,
	pareshTalk,
	abhinoy,
} from "../../../../../assets";

export const data = [
	{
		title: "Forecasting Crude Oil Futures Prices Using the Kalman Filter and News",
		time: "2:00 PM - 3:00 PM IST",
		speakers: [
			{
				name: "Dr. Paresh Date",
				designation:
					"Director of Research and Head of Financial Mathematics and Operational Research (FOR) group.",
				desc: "Dr. Paresh Date is Reader in the Department of Mathematics, College of Engineering, Design and Physical Sciences at Brunel University. He is currently the Head of Financial Mathematics, Operational Research (FOR) group and Director of Research in the Department. His main research interest is developing algorithms for latent state estimation or filtering in nonlinear time series and applications of filtering, especially in mathematical finance. Besides this key topic, He has a diverse research portfolio which includes efficient ways of computing tail distributions in financial portfolios of nonlinear instruments, scenario generation and system identification.",
				img: paresh,
			},
		],
		img: pareshTalk,
		venue: "Google Meet",
		desc: "This talk looks at an empirical application of a mathematical tool familiar to engineers and mathematicians in a less familiar area. In particular, the speaker will be looking at forecasting the prices of certain financial derivative products called futures, using the Kalman filter. The annual trade volume in global futures markets is over 11 trillion USD (around three times India's GDP), so that accurate short-term forecasting of futures prices is an important practical problem. The speaker will also look at enhancing the results of Kalman filter-based forecasting using an exogenous source of information (news sentiment), which falls under the moniker 'explainable AI'. Moreover, he will demonstrate results of numerical experiments with real financial market data. This talk should provide a window to the fascinating world of financial mathematics for mathematicians and engineers.",
		date: "27th August, 2021",
		oc: [
			{
				name: "Dr. Abhinoy Kumar Singh",
				designation: "Department of Electrical Engineering, IIT Indore",
				img: abhinoy,
			},
		],
		name: "paresh-date",
	},
	{
		title: "A public Lecture by Prof. Bruce C. Berndt from the University of Illinois at Urbana-Champaign, USA",
		time: "7:30 PM IST",
		speakers: [
			{
				name: "Prof. Bruce C. Berndt",
				designation: "University of Illinois, Urbana-Champaign, USA",
				desc: "Prof. Bruce C. Berndt is one of the world's foremost mathematicians in the work of Srinivasa Ramanujan. Prof. Berndt received Ph.D. from the University of Wisconsin in 1966. After an Assistant Lectureship at the University of Glasgow for one year, he joined as an Assistant Professor at the University of Illinois in 1967. During his 52 years of teaching and research at UIUC, he has supervised 37 doctoral students and published more than 270 research papers. In 1996, Prof. Berndt received the Steel Prize from the American Mathematical Society for editing Ramanujan's Notebooks. He published five volumes on Ramanujan's notebooks with Springer during 1985-1998, and then together with Prof. George Andrews, he published five volumes on Ramanujan's lost notebook with Springer during 2005-2018. Prof. Berndt is the founding editor of the International Journal of Number Theory.",
				img: bruce,
			},
		],
		img: FLYER_Maths_Seminar,
		venue: "Webex",
		desc: "Link for Live Streaming: https://iiti.ac.in/live\nWebex Link: https://iiti.webex.com/meet/seminar_maths\nWe begin with an account of Ramanujan’s life. Histories of Ramanujan’s (earlier) notebooks and lost notebook will be given. I will then describe my involvement with Ramanujan’s notebooks and lost notebook during the past 47 years. The lecture will conclude with some examples taken from Ramanujan’s notebooks and his lost notebook. Most of the lecture will be accessible to a general audience.",
		date: "5th October, 2021",
		oc: [
			{ name: "Dr. Ashisha Kumar", designation: "Department of Mathematics, IIT Indore", img: ashisha },
			{ name: "Dr. Santanu Manna", designation: "Department of Mathematics, IIT Indore", img: manna },
			{ name: "Dr. Bibekananda Maji", designation: "Department of Mathematics, IIT Indore", img: bibek },
		],
		name: "bruce-berndt",
	},
	{
		title: "Automotive Light-weighting Technologies",
		time: "6.30 pm",
		speakers: [
			{
				name: "Prof. Raghu Echempati",
				designation: "Professor, Kettering University Flint, MI, USA",
				img: ProfRaghu,
				desc: "Dr. Echempati’s academic career spans over 3 decades as he taught at many Universities in USA and abroad since 1976. These included IIT Delhi, Universityof Florida, The Ohio State University, etc., before joining Kettering University in 1997. He is a member of ASME, ASEE, and SAE. He taught at various universities world-wide as a Fulbright scholar, Erskine fellow, or as a visiting professor. He won several academic and technical awards and grants. He has published over 160 applied research papers in peer-reviewed journals and conference proceedings of repute. He has supervised over 250 undergraduate/graduate and research student theses, reviewed several technical articles, papers, textbooks and research proposals for various domestic and international conferences, journals, scientific bodies and publishers",
			},
		],
		img: automative,
		venue: "Webex",
		desc: "Automotive industry traditionally has reduced weight primarily by downsizing. Today, the strategy of downsizing vehicle has reached its limits. The OEMs are also facing substantial increases in Corporate Average Fuel Economy (CAFE) regulations in the U.S. and the other global markets. In this context, engineering students need to understand the underlying contributors that significantly play a role in vehicle Light-weighting. One of the main contributors is the appropriate use of a variety of high strength and lightweight materials to meet the mass (weight) targets. Another aspect and a more challenging issue is that a realization of how OEMs are learning to cost effectively join (weld, rivet, form and cast) lightweight (and often multi) materials on a global platform. How to impart these ideas intoa single platform? The purpose of this talk is to discuss the need and strategic development of undergraduate and graduate level coursematerials on this topic and the best assessment techniques to gauge the understanding of the topics by the students. The teaching and learning experiences of the Prof. Raghu in delivering this webinar is related mechanical student and to general technicalaudience.",
		date: "22nd February, 2021",
		oc: [
			{
				name: "Dr. Satyanarayan Patel",
				designation: "Convener",
				img: spatel,
			},
			{
				name: "Dr. Harekrishna Yadav",
				designation: "Member",
				img: harekrishna,
			},
			{
				name: "Dr. Ashish Rajak",
				designation:
					"Member & Department of Mechanical Engineering Indian Institute of Technology Indore Indore, India",
				img: ashish,
			},
		],
		name: "automotive",
	},
	{
		title: "Prosperity Through Science Technology",
		time: "3.30 pm",
		speakers: [
			{
				name: "Prof. J. B. Joshi",
				designation: "",
				img: joshi,
				desc: "Prof. J. B. Joshi is an Emeritus Professor of Eminence, Institute of Chemical Technology, Mumbai. He has about 20 innovations and 600+ international publications to his credit. Prof. Joshi hasdeveloped novel processes, designs, products and implemented in large, medium and small-scale industry. Designed more than 1000 reactors and extensively participated in Process intensification.His research and teaching interest includeFluid Mechanics, Multiphase Reactor Design, Computational Fluid Dynamics,Atomic Energy, Solar Energy&Bio-Energy.He is the fellow of the FTWNS, FNA, FASc, FNAE and FNASc. He has been bestowed with several awards which include Shantiswarup Bhatnagar Prize forEngineering Sciences, 1991; Padma Bhushan Award, Government of India, 2014; Lifetime Achievement Award, 2017 and many more.",
			},
		],
		img: scitech,
		venue: "Webex",
		desc: "Science-including biological, physical, social, behavioral, cultural, engineering, and medical disciplines play an increasingly important role in governmental and institutional response during crises. During global crises the role of scientific community becomes even more critical in nation building by identifying critical problems, determine how our capability can be best used to answer those questions, design and execute the necessary research, and then share those results with decision-makers and the public. The ongoing Covid-19 pandemic has brought to the fore the importance of a thriving scientific ecosystem for dealing with global crises.The popular public lecture series will bring together a group of eminent experts around the world to share their views on the role of science, research, education, and actionable data in nation building during global health crisis. ",
		date: "5th February, 2021",
		oc: [
			{
				name: "Prof. Avinash Sonawane",
				designation:
					"Department of Biosciences and Biomedical Engineering, Dean of International Affairs Outreach, IIT Indore, India",
				img: avinash,
			},
			{
				name: "Prof. Tone Tonjum",
				designation: "Department of Microbiology, University of Oslo, Norway",
				img: toneTonjum,
			},
		],
		name: "prosperity",
	},
	{
		title: "Role of Science in Nation Building during Global Health Crisis (IV)",
		time: "4:30 PM IST",
		speakers: [
			{
				name: "Prof. Gagandeep Kang",
				designation:
					"Professor of Microbiology Wellcome Trust Research Laboratory Division of Gastrointestinal Sciences Christian Medical College, Vellore, India",
				desc: "Professor Kang conducts inter-disciplinary research on viral infections, nutrition and child health. Her team has evaluated vaccines in pre-clinical and clinical phase 1-3 trials for enteric infections and coordinated multi-site surveillance studies to develop national disease burden estimates. She is a member of many WHO advisory committees, is the vice-Chair of the Board of Coalition of Epidemic Preparedness Innovations and chairs the Immunization Technical Advisory Group for the WHO’s South East Asian Region. She also served as Executive Director, Translational Health Science and Technology Institute, Faridabad, an autonomous institute of the DBT, Government of India. She was awarded the prestigious Infosys Prize in Life Sciences for her contributions to understanding the history of rotavirus and other infectious diseases. In 2019, she became the first Indian woman to be elected as a Fellow of the Royal Society.",
				img: gagandeep,
			},
		],
		img: global_health_crisis_iv,
		venue: "Webex",
		desc: "IIT Indore in association with University of Oslo is organizing a public lecture series on the topic “Role of Science in Nation Building during Global Health Crisis”. This event is sponsored by INTPART, Research Council of Norway.\nScience-including biological, physical, social, behavioral, cultural, engineering, and medical disciplines play an increasingly important role in governmental and institutional response during crises. During global crises the role of scientific community becomes even more critical in nation building by identifying critical problems, determine how our capability can be best used to answer those questions, design and execute the necessary research, and then share those results with decision-makers and the public. The ongoing Covid-19 pandemic has brought to the fore the importance of a thriving scientific ecosystem for dealing with global crises. The popular public lecture series will bring together a group of eminent experts around the world to share their views on the role of science, research, education, and actionable data in nation building during global health crisis.\nIn this way, we plan to establish a large virtual academic platform that will include participants not only from premier institutes in India but will also involve participation of students and young faculties from a group of institutions, which have limited scientific exposure in terms of research and higher education largely due to their presence at remotest part of India.",
		date: "15th September, 2021",
		oc: [
			{
				name: "Prof. Avinash Sonawane",
				designation:
					"Department of Biosciences and Biomedical Engineering & Dean, International Affairs & Outreach, IIT Indore, India",
				img: avinash,
			},
			{
				name: "Prof. Tone Tonjum",
				designation: "Department of Microbiology, University of Oslo, Norway",
				img: toneTonjum,
			},
		],
		name: "health",
	},
	{
		title: "Nobel Prizes-2020",
		time: "11am onwards",
		speakers: [
			{
				name: "Prof. Somak Raychaudhury",
				designation: "Director, Inter-University Centre for Astronomy and Astrophysics, Pune",
				img: somak,
				desc: "Nobel Prize in Physics",
			},
			{
				name: "Prof. G. N. Sastry",
				designation: "Director CSIR NEIST, Jorhat",
				img: sastry,
				desc: "Nobel Prize in Chemistry",
			},
			{
				name: "Dr. Jeevant Rampal",
				designation: "Professor, IIM, Ahmedabad",
				img: jeevant,
				desc: "Nobel Prize in Economics",
			},
			{
				name: "Prof Shormistha Panja",
				designation: "Professor of Literature and Director of the Centre for Learning, Delhi University",
				img: shor,
				desc: "Nobel Prize in Literature",
			},
			{
				name: "Mr. Bishow Parajuli",
				designation: "Country Director, UN World Food Programme",
				img: bishow,
				desc: "Nobel Prize in Peace",
			},
			{
				name: "Prof. Saumitra Das",
				designation: "Director, National Institute of Biomedical Genomics, Kalyani, WB",
				img: saumitra,
				desc: "Nobel Prize in Medicine",
			},
		],
		img: nobel,
		venue: "Webex",
		desc: "",
		date: "21-24 December, 2020",
		oc: [
			{
				name: "Dr. Raghunath Sahoo",
				designation: "Convener, Institute Outreach and Associate Dean International Affairs and Outreach",
				img: raghu,
			},
			{
				name: "Prof. Biswarup Pathak",
				designation: "Professor, Chemistry",
				img: biswarup,
			},
			{
				name: "Prof. Ruchi Sharma",
				designation: "Professor, Economics",
				img: ruchi,
			},
			{
				name: "Prof. Nirmala Menon",
				designation: "Literature/Peace",
				img: nirmala,
			},
			{
				name: "Prof. Prashant Kodgire",
				img: prashant,
				designation: "Medicine",
			},
			{
				name: "Prof. Debasis Nayak",
				designation: "Medicine",
				img: debasis,
			},
		],
		name: "nobelPrizes",
	},
	{
		title: "Frontiers in Physics (Public Lecture Series-2020)",
		name: "frontiers",
		time: "11am",
		speakers: [
			{
				name: "Professor Srubabati Goswami",
				designation: "FASc, FNASc, FNA (Physical Research Laboratory, Ahmedabad)",
				img: srubabati,
				desc: "Title: The Mystery of the Missing Antimatter in the Universe\n(March 2021: To be announced)",
			},
			{
				name: "Professor H.S. Mani",
				designation: "FNASc, FASc (Chennai Mathematical Institute)",
				img: mani,
				desc: "Title: Physics of Information\n(19 December 2020)",
			},
			{
				name: "Professor Amol Dighe",
				designation: "FASc, FNA (Tata Institute of Fundamental Research, Mumbai)",
				img: amol,
				desc: "Title: Neutrinos: A new window to see the Universe\n(04 December 2020)",
			},
			{
				name: "Professor Ajoy Ghatak",
				designation:
					"FNASc (Meghnad Saha Professor, The National Academy of Sciences, India and Formerly Professor of Physics @ IIT Delhi)",
				img: ajoy,
				desc: "Title: Light & Einstein’s E = mc2\n(10 November 2020)",
			},
			{
				name: "Professor S. M. Yusuf",
				designation: "FASc, FNASc (BARC, Mumbai IoP, Bhubaneswar)",
				img: yusuf,
				desc: "Title: Neutrons for Material Research and Technology\n(17 October 2020)",
			},
			{
				name: "Professor Amit Roy",
				designation: "FNASc (Ex-IUAC, New Delhi)",
				img: amit,
				desc: "Title: QUEST FOR THE MICROWORLD: Story of Nuclei, Particles & Accelerators\n(25 September 2020)",
			},
			{
				name: "Professor Bedangadas Mohanty",
				designation: "FNA, FASc, FNASc (NISER, Bhubaneswar)",
				img: bm,
				desc: "Title: Little Bang and Femto-Nova in Nucleus-Nucleus Collisions\n(18 September 2020)",
			},
			{
				name: "Professor Sunil K. Gupta",
				designation: "FNASc (Tata Institute of Fundamental Research, Mumbai)",
				img: sunilGupta,
				desc: "Title: Solar Storms and Their Impact on Earth, Studied through Muons\n(10 September 2020)",
			},
			{
				name: "Professor Tarun Souradeep",
				designation: "FASc, FNASc (IISER Pune, LIGO-India Spokesperson)",
				img: tarun,
				desc: "Title: LIGO-India: Ushering in Gravitational Wave Astronomy\n(25 August 2020)",
			},
			{
				name: "Professor Dinesh Kumar Srivastava",
				designation: "FNA, FNASc (Homi Bhabha Chair Professor, NIAS, Bengaluru)",
				img: dks,
				desc: "Title: Climate Change and Energy Options for a Sustainable Future\n(30 June 2020)",
			},
		],
		img: physics,
		venue: "Webex",
		desc: "",
		date: "30 June onwards",
		oc: [
			{
				name: "Dr. Raghunath Sahoo",
				designation: "Convener, Institute Outreach and Associate Dean IAO",
				img: raghu,
			},
		],
	},
	{
		title: "Hardy-Ramanujan Lecture Series in Mathematics",
		name: "ramanujan",
		time: "11am",
		speakers: [
			{
				name: "Prof. Atul Dixit",
				designation: "IIT Gandhinagar",
				img: person,
				desc: "Excepteur sint ullamco proident sunt. Consectetur cupidatat commodo non adipisicing aliquip veniam laboris irure amet enim excepteur ut dolor. Minim velit exercitation anim elit quis sit consequat non sit culpa sunt minim. Aliquip est qui ex eu quis amet esse proident adipisicing est in laborum. Laborum laboris occaecat eu occaecat sunt ex ex ex. Fugiat mollit aliqua pariatur eu. Proident amet officia veniam qui nostrud commodo labore est id.",
			},
			{
				name: "Prof. Nayandeep Deka Baruah",
				designation: "Tezpur University",
				img: person,
				desc: "Excepteur sint ullamco proident sunt. Consectetur cupidatat commodo non adipisicing aliquip veniam laboris irure amet enim excepteur ut dolor. Minim velit exercitation anim elit quis sit consequat non sit culpa sunt minim. Aliquip est qui ex eu quis amet esse proident adipisicing est in laborum. Laborum laboris occaecat eu occaecat sunt ex ex ex. Fugiat mollit aliqua pariatur eu. Proident amet officia veniam qui nostrud commodo labore est id.",
			},
		],
		img: ramanujan,
		venue: "Webex",
		desc: "",
		date: "Throughout the year.",
		oc: [
			{ name: "Dr. Ashisha Kumar", designation: "Convener", img: person },
			{ name: "Dr. Santanu Manna", designation: "", img: person },
			{ name: "Dr. Bibekananda Maji", designation: "", img: person },
		],
		linkDisabled: true,
	},
	{
		title: "Borametallomimetics - Activation of Small Molecules by Low-valent Boron Species",
		name: "borametallomimetics",
		time: "9pm",
		speakers: [
			{
				name: "Prof. Dr. Holger",
				designation: "Professor, Braunschweig University of Würzburg, Germany",
				img: holger,
				desc: "",
			},
		],
		img: boron,
		venue: "Webex",
		desc: "India celebrates the “National Science Day” on 28th February to mark the discovery of the Raman effect by Sir C. V. Raman. On this occasion, the Department of Chemistry, Indian Institute of Technology Indore is organizing Chemistry Lectures. In the month of February, chemistry-based research talks from several eminent speakers across the world have been scheduled.\nChemistry Lectures aim to provide a platform for eminent chemists from all over the world to share and discuss wider aspects of the domain of chemical sciences and allied areas. The webinar is expected to provide a unique opportunity to establish new and ever-lasting bonding between the researchers, and inspire the young students to explore new ways to understand chemistry and its interface.",
		date: "February, 2021",
		oc: [
			{
				name: "Dr. Dipak Kumar Roy",
				designation: "Department of Chemistry Indian Institute of Technology Indore Indore, India",
				img: dipak,
			},
		],
		linkDisabled: true,
	},
	{
		title: "New photocatalytic reactions: Updates on radical cascades and photooxygenations",
		name: "photocatalytic",
		time: "9pm",
		speakers: [
			{
				name: "Prof. Dr. Malte Brasholz",
				designation: "Professor, University of Rostock, Germany",
				img: malte,
				desc: "",
			},
		],
		img: photocat,
		venue: "Webex",
		desc: "India celebrates the “National Science Day” on 28th February to mark the discovery of the Raman effect by Sir C. V. Raman. On this occasion, the Department of Chemistry, Indian Institute of Technology Indore is organizing Chemistry Lectures. In the month of February, chemistry-based research talks from several eminent speakers across the world have been scheduled.\nChemistry Lectures aim to provide a platform for eminent chemists from all over the world to share and discuss wider aspects of the domain of chemical sciences and allied areas. The webinar is expected to provide a unique opportunity to establish new and ever-lasting bonding between the researchers, and inspire the young students to explore new ways to understand chemistry and its interface.",
		date: "February, 2021",
		oc: [
			{
				name: "Dr. Dipak Kumar Roy",
				designation: "Department of Chemistry Indian Institute of Technology Indore Indore, India",
				img: dipak,
			},
		],
		linkDisabled: true,
	},
	{
		title: "Organometallic Wires for Electronics",
		name: "organometallic",
		time: "9pm",
		speakers: [
			{
				name: "Prof. Jean-François Halet",
				designation:
					"Professor, Université de Rennes, CNRS, ISCR (Institut des Sciences Chimiques de Rennes), France",
				img: halet,
				desc: "",
			},
		],
		img: organo,
		venue: "Webex",
		desc: "India celebrates the “National Science Day” on 28th February to mark the discovery of the Raman effect by Sir C. V. Raman. On this occasion, the Department of Chemistry, Indian Institute of Technology Indore is organizing Chemistry Lectures. In the month of February, chemistry-based research talks from several eminent speakers across the world have been scheduled.\nChemistry Lectures aim to provide a platform for eminent chemists from all over the world to share and discuss wider aspects of the domain of chemical sciences and allied areas. The webinar is expected to provide a unique opportunity to establish new and ever-lasting bonding between the researchers, and inspire the young students to explore new ways to understand chemistry and its interface.",
		date: "February, 2021",
		oc: [
			{
				name: "Dr. Dipak Kumar Roy",
				designation: "Department of Chemistry Indian Institute of Technology Indore Indore, India",
				img: dipak,
			},
		],
		linkDisabled: true,
	},
	{
		title: "Nanoparticle-Derived Functional Materials and Model Catalysts",
		name: "nanoparticle",
		time: "9pm",
		speakers: [
			{
				name: "Prof. Dr. Silke Behrens",
				designation: "IKFT, Karlsruhe Institute of Technology (KIT), Germany",
				img: silke,
				desc: "",
			},
		],
		img: nano,
		venue: "Webex",
		desc: "India celebrates the “National Science Day” on 28th February to mark the discovery of the Raman effect by Sir C. V. Raman. On this occasion, the Department of Chemistry, Indian Institute of Technology Indore is organizing Chemistry Lectures. In the month of February, chemistry-based research talks from several eminent speakers across the world have been scheduled.\nChemistry Lectures aim to provide a platform for eminent chemists from all over the world to share and discuss wider aspects of the domain of chemical sciences and allied areas. The webinar is expected to provide a unique opportunity to establish new and ever-lasting bonding between the researchers, and inspire the young students to explore new ways to understand chemistry and its interface.",
		date: "February, 2021",
		oc: [
			{
				name: "Dr. Dipak Kumar Roy",
				designation: "Department of Chemistry Indian Institute of Technology Indore Indore, India",
				img: dipak,
			},
		],
		linkDisabled: true,
	},
	{
		title: "Atomic Clocks",
		name: "atomic",
		time: "9:40-11:30 AM IST",
		speakers: [
			{
				name: "Prof. David J. Wineland",
				designation: "Nobel Laureate in Physics, 2012",
				desc: "Prof. David Jeffrey Wineland, is an American Nobel-laureate physicist at the National Institute of Standards and Technology (NIST) Physics laboratory. His work included advances in optics, specifically laser-cooling trapped ions and using ions for quantum- computing operations. He was awarded the 2012 Nobel Prize in Physics, jointly with Prof. Serge Haroche, for 'ground-breaking experimental methods that enable measuring and manipulation of individual quantum systems'. Prof. Wineland was born in Wauwatosa, Wisconsin on February 24, 1944. Prof. Wineland graduated from Encina High School in Sacramento in 1961. He received his bachelor's degree in Physics from the University of California, Berkeley in 1965 and his master's and doctoral degrees in Physics from Harvard University. He completed his PhD in 1970, supervised by Norman Foster Ramsey, Jr. He then performed postdoctoral research in Hans Dehmelt's group at the University of Washington where he investigated electrons in ion traps. In January 2018, Prof. Wineland moved to the Department of Physics University of Oregon as a Knight Research Professor, while still being engaged with the Ion Storage Group at NIST in a consulting role. His NIST group uses trapped ions in many experiments on fundamental Physics, and quantum state control. They have demonstrated optical techniques to prepare ground, superposition and entangled states. This work has led to advances in spectroscopy, atomic clocks and quantum information. In 1995, he created the first single atom quantum logic gate and was the first to quantum teleport information in massive particles in 2004. Prof. Wineland implemented the most precise",
				img: Professor_David,
			},
		],
		img: grp3,
		venue: "Webex",
		desc: "",
		date: "23rd February, 2021",
		oc: [
			{
				name: "Dr. Raghunath Sahoo",
				designation: "Convener, Institute Outreach and Associate Dean IAO",
				img: raghu,
			},
		],
	},
	{
		title: "The revolutionary quantum reform of the international metric system",
		name: "quantumReform",
		time: "9:30-11:30 AM IST",
		speakers: [
			{
				name: "Prof. William D. Phillips",
				designation: "Nobel Laureate in Physics, 1997",
				desc: "Prof. Phillips was born to William Cornelius Phillips of Juniata, Pennsylvania and Mary Catherine Savino of Ripacandida, Italy. He graduated from Juniata College in 1970 summa cum laude. After that he received his physics doctorate from the Massachusetts Institute of Technology. In 1978 he joined NIST. In 1996, he received the Albert A. Michelson Medal from The Franklin. Prof. Phillips doctoral thesis concerned the magnetic moment of the proton in H 2 O. He later did some work with Bose–Einstein condensates. In 1997, he won the Nobel Prize in Physics together with Prof. Claude Cohen-Tannoudji and Prof. Steven Chu for his contributions to laser cooling, a technique to slow the movement of gaseous atoms in order to better study them, at the National Institute of Standards and Technology, and especially for his invention of the Zeeman slower. Prof. Phillips is also a Professor of Physics, at University of Maryland, College Park.",
				img: Prof_William,
			},
		],
		img: grp3,
		venue: "Webex",
		desc: "",
		date: "17th February, 2021",
		oc: [
			{
				name: "Dr. Raghunath Sahoo",
				designation: "Convener, Institute Outreach and Associate Dean IAO",
				img: raghu,
			},
		],
	},
];
