export const data = {
	asia: [
		{
			"S.No.": 1,
			"Institutions/Organization/Country": "Shinshu University Japan",
			Nature: "MoU",
			"Purpose/Title": "Academic Cooperation and Exchange of students",
			"Coordinating faculty member": "DOIA\nDOAA",
			"Signed on": "July 28, 2020",
			Duration: "5 Years",
			"Country with which there is collation": "Japan",
		},
		{
			"S.No.": 2,
			"Institutions/Organization/Country": "Rajamangala University of Technology PHRA Nakhon",
			Nature: "MoU",
			"Purpose/Title":
				"Exchanging of scholars, students, academic information and materials to enhance the research and educational process",
			"Coordinating faculty member": "DOIA\nDOAA\nDORD",
			"Signed on": "Febr/uary 20,2020",
			Duration: "5 Years",
			"Country with which there is collation": "Thailand",
		},
		{
			"S.No.": 3,
			"Institutions/Organization/Country": "Thammsasat University Bangkok Thailand",
			Nature: "MoU",
			"Purpose/Title":
				"Exchange of students, scholars, researchers and staff;\nCollaborative activities such as joint research, lectures, and symposium; \nSharing of information, publications, documents, and research materials in fields of mutual interest;\nOther mutually beneficial Projects;",
			"Coordinating faculty member": "DOIA\nDORD\nHOD, CE",
			"Signed on": "December 24, 2019",
			Duration: "5 Years",
			"Country with which there is collation": "Thailand",
		},
		{
			"S.No.": 4,
			"Institutions/Organization/Country": "Chonnam National  University, Korea",
			Nature: "MoU",
			"Purpose/Title": "Cooperation in Academic and Research Related Activities;",
			"Coordinating faculty member": "DOIA\nDOAA\nDOFA\nDORD",
			"Signed on": "March 15, 2018",
			Duration: "5 Years",
			"Country with which there is collation": "Korea",
		},
		{
			"S.No.": 5,
			"Institutions/Organization/Country": "Nagaoka University of Technology",
			Nature: "Agreement",
			"Purpose/Title":
				"The exchange of academic, research, and administrative staffs; \nThe exchange of students; \nJoint research on scientific and technological subjects; \nJoint scientific and technological meetings, symposiums, workshops, conferences, and lectures; \nThe exchange of academic findings, publications, and other academic and educational information as appropriate; \nand  Other academic and educational collaboration and exchange as approved by the two universities/ institutes.",
			"Coordinating faculty member": "DOIA\nDOAA",
			"Signed on": "July 6, 2018",
			Duration: "5 Years",
			"Country with which there is collation": "Japan",
		},
		{
			"S.No.": 6,
			"Institutions/Organization/Country":
				"Graduate School of Life Science and Systems Engineering, Kyushu Institute of Technology, Japan",
			Nature: "MoU",
			"Purpose/Title":
				"Exchange of students, faculty members for research, discussion and lectures; \nJoint research activities; \nExchanges of academic materials",
			"Coordinating faculty member": "DOIA\nDOAA\nDOFA",
			"Signed on": "April 18, 2018",
			Duration: "5 Years",
			"Country with which there is collation": "Japan",
		},
		{
			"S.No.": 7,
			"Institutions/Organization/Country": "National Dong Hwa University, Taiwan, R.O.C",
			Nature: "MoU",
			"Purpose/Title":
				"Students and academic and administrative staff exchanges; \nJoint research activities; \nExchanges of academic materials",
			"Coordinating faculty member": "DOIA\nDOAA\nDORD",
			"Signed on": "November 24, 2017",
			Duration: "",
			"Country with which there is collation": "Taiwan",
		},
		{
			"S.No.": 8,
			"Institutions/Organization/Country": "Jeju National University, Korea",
			Nature: "MoU",
			"Purpose/Title": "Academics",
			"Coordinating faculty member": "DOIA\nDr. Shaibal Mukherjee",
			"Signed on": "June 26, 2017",
			Duration: "5 Years",
			"Country with which there is collation": "Korea",
		},
		{
			"S.No.": 9,
			"Institutions/Organization/Country": "Ming Chi University Of Technology, Taiwan",
			Nature: "MoU",
			"Purpose/Title":
				"Academic and Research Collaboration, Scholarship Program to Ph.D. students       \nunder Joint Supervision",
			"Coordinating faculty member": "DOIA\nDOAA\nDr. I. A. Palani",
			"Signed on": "May 8, 2017",
			Duration: "5 Years",
			"Country with which there is collation": "Taiwan",
		},
		{
			"S.No.": 10,
			"Institutions/Organization/Country": "Enricssion Co. Ltd.",
			Nature: "MoU",
			"Purpose/Title": "Establishment of Shiru Café at IIT",
			"Coordinating faculty member": "DOAA\nHOS, HSS",
			"Signed on": "March 4, 2016",
			Duration: "",
			"Country with which there is collation": "Japan",
		},
		{
			"S.No.": 11,
			"Institutions/Organization/Country":
				"Ming Chi University of Technology, New Taipei, Taiwan",
			Nature: "MoU",
			"Purpose/Title": "Academic and Research Collaboration",
			"Coordinating faculty member": "Registrar",
			"Signed on": "February 11, 2016",
			Duration: "5 Years",
			"Country with which there is collation": "Taiwan",
		},
		{
			"S.No.": 12,
			"Institutions/Organization/Country": "Kyushu Institute of Technology, Japan",
			Nature: "MoU",
			"Purpose/Title": "Academic",
			"Coordinating faculty member": "DOIA\nDOAA",
			"Signed on": "June 11, 2012",
			Duration: "5 Years",
			"Country with which there is collation": "Japan",
		},
	],
	americas: [
		{
			"Institutions/Organization/Country": "Fundacao Universidade De Caxias Do Sul",
			Nature: "MoU",
			"Purpose/Title":
				"Exchange programs for Professors, Researchers, Students, Administrators, and technical person;\nJoint development of projects and research;\nDevelopment of scholarship programs;\nActivities of attainment of graduate and Post-graduate academic levels.\nExchange of bibliography, programs, didactic, technical and scientific material;\nElaboration of scientific articles and other publications;\nOther forms of cooperation agreed by the parties.",
			"Coordinating faculty member": "Dr. Bhupesh Lad",
			"Signed on": "February 12, 2019",
			Duration: "5 Years",
			"Country with which there is collation": "Brazil",
		},
		{
			"Institutions/Organization/Country": "Oregon State University",
			Nature: "MoU",
			"Purpose/Title":
				"Exchange of students, faculty members for research, discussion, and lectures;\nJoint research activities;\nExchanges of academic materials",
			"Coordinating faculty member": "DOIA\nDOAA\nDORF\nDr. Rupesh S. Devan",
			"Signed on": "May 15, 2018",
			Duration: "5 Years",
			"Country with which there is collation": "United States",
		},
		{
			"Institutions/Organization/Country": "UT-Battelle, LLC",
			Nature: "Non-Proprietary User Agreement",
			"Purpose/Title":
				'The operator of Oak Ridge National Laboratory ( hereinafter "Laboratory" or "ORNL" under Prime contract No. DE-AC05-00OR22725 with the United States Government( hereinafter "U.S. Government" or "Government"), as represented by the United States Department of Energy (hereinafter "DOE") and IIT Indore',
			"Coordinating faculty member": "DOIA\nDOAA\nDORD",
			"Signed on": "July 27, 2017",
			Duration: "5 Years",
			"Country with which there is collation": "USA",
		},
		{
			"Institutions/Organization/Country": "The University of Wiscosin, Madison, USA",
			Nature: "MoU",
			"Purpose/Title": "Specific Astro Physical Research Projects",
			"Coordinating faculty member": "DOIA\nDOAA",
			"Signed on": "January 28, 2013",
			Duration: "10 Years",
			"Country with which there is collation": "USA",
		},
		{
			"Institutions/Organization/Country": "Uchicago, Argonne LLC, IL, USA",
			Nature: "MoU",
			"Purpose/Title": "Academic",
			"Coordinating faculty member": "DOIA\nDORD\nHOD, AASSE",
			"Signed on": "December 5, 2012",
			Duration: "5 Years",
			"Country with which there is collation": "USA",
		},
		{
			"Institutions/Organization/Country": "University of Wisconsin-Milwaukee, USA",
			Nature: "MoU",
			"Purpose/Title": "Academic",
			"Coordinating faculty member": "DOIA\nDOAA",
			"Signed on": "October 3, 2012",
			Duration: "Till mutually agreed",
			"Country with which there is collation": "USA",
		},
		{
			"Institutions/Organization/Country": "New Mexico State University, USA",
			Nature: "MoU",
			"Purpose/Title": "Academic",
			"Coordinating faculty member": "DOIA\nDOAA",
			"Signed on": "October 1, 2012",
			Duration: "5 Years",
			"Country with which there is collation": "USA",
		},
	],
	australia: [
		{
			"S.No.": 1,
			"Institutions/Organization/Country": "Univesity of Technology Sydney",
			Nature: "MoU",
			"Purpose/Title":
				"Visits by and exchange of students for the purpose of research; Visits by interchange of staff for the purposes of research, teaching, and discussions;\nJoint research activities; \nJoint participation in internationally funded research projects;",
			"Coordinating faculty member": "DOIA\nDOAA\nDORD",
			"Signed on": "October 24, 2019",
			Duration: "5 Years",
			"Country with which there is collation": "Sydney",
		},
		{
			"S.No.": 2,
			"Institutions/Organization/Country": "Edith Cowan University, Perth Australia",
			Nature: "MoU",
			"Purpose/Title":
				"Research visit of faculty members, Research Scientists, Postdoctoral Associates, and students \nJoint supervision of M.S. and Ph.D. students\nDevelopment of curricula\nPromote international cooperation and academic exchange",
			"Coordinating faculty member": "DOIA\nDOAA\nDr. Bhargava Vaidya",
			"Signed on": "May 23, 2019",
			Duration: "5 Years",
			"Country with which there is collation": "Australia",
		},
		{
			"S.No.": 3,
			"Institutions/Organization/Country": "Deakin University, Australia",
			Nature: "MoU",
			"Purpose/Title":
				"Research activities, possible short-course programs and joint research degree",
			"Coordinating faculty member": "DOIA\nDORD\nDr. Raghunath Sahoo",
			"Signed on": "March 6, 2013",
			Duration: "5 Years",
			"Country with which there is collation": "Australia",
		},
	],
	europe: [
		{
			"S.No.": 1,
			"Institutions/Organization/Country": "Western Norway Research Institute",
			Nature: "Agreement",
			"Purpose/Title":
				"Transnational Partnership for Excellent Research and Education in Disruptive Technologies for a resilient future",
			"Coordinating faculty member": "DORD",
			"Signed on": "August 11, 2020",
			Duration: "3 Years",
			"Country with which there is collation": "Norway",
		},
		{
			"S.No.": 2,
			"Institutions/Organization/Country": "University of Florence, Italy",
			Nature: "Agreement",
			"Purpose/Title":
				"Cultural and Scientific Cooperation between the dept of earth sciences",
			"Coordinating faculty member": "DOIA\nDORD\nHOD, CE",
			"Signed on": "December 23, 2019",
			Duration: "7 years",
			"Country with which there is collation": "Italy",
		},
		{
			"S.No.": 3,
			"Institutions/Organization/Country":
				"Insitut National Polytechnique de Toulouse France",
			Nature: "Agreement",
			"Purpose/Title":
				"Exchange of materials in education and research, in particular, to promote international information;                                                                                                                              Exchange of faculty members and Research Scholars;\nOne way exchange of students;\nJoint research and meetings for education and research;                                                         \nTechnical assistance;                                                                                                          Utilizing a hybrid online learning model for graduate training;",
			"Coordinating faculty member": "DOIA\nDOAA",
			"Signed on": "October 23, 2019",
			Duration: "5 Years",
			"Country with which there is collation": "France",
		},
		{
			"S.No.": 4,
			"Institutions/Organization/Country":
				"Max Planck Institute for Astronomy, Heidelberg, Germany",
			Nature: "Collaborative Agreement",
			"Purpose/Title":
				"To perform collaborative research activities according to the collaborative research program",
			"Coordinating faculty member": "DOIA\nDOAA\nDOFA",
			"Signed on": "July 1, 2019",
			Duration: "3 Years",
			"Country with which there is collation": "Germany",
		},
		{
			"S.No.": 5,
			"Institutions/Organization/Country": "Uppsala Universitet",
			Nature: "MoU",
			"Purpose/Title":
				"Exchange of faculty members, Postdoctoral Associates, Research Scholars, and Master Students\nJoint supervision of M.S. and Ph.D. students\nDevelopment of curricula\nExchange of academic information and materials Exchange of periodicals and other publications\nOrganization of joint research programs, conferences",
			"Coordinating faculty member": "DOIA\nDOAA\nHOD, HSS",
			"Signed on": "April 24, 2019",
			Duration: "5 Years",
			"Country with which there is collation": "Sweden",
		},
		{
			"S.No.": 6,
			"Institutions/Organization/Country": "Royal Academy of Engineering",
			Nature: "MoU",
			"Purpose/Title":
				"To support the aims of the UK government’s Newton Fund by facilitating international visits and exchanges between industry and academic partners in the UK and their counterparts in elected Newton Fund Partner Countries",
			"Coordinating faculty member": "DOIA\nDOAA\nHOD, Chemistry",
			"Signed on": "March 14, 2019",
			Duration: "2 Years",
			"Country with which there is collation": "London",
		},
		{
			"S.No.": 7,
			"Institutions/Organization/Country": "INSTITUT Mines-Telecom, France",
			Nature: "MoU",
			"Purpose/Title":
				"To foster academic and scientific collaboration  \nProvide opportunity for global experience \nFacilitate the advancement of knowledge on the basis of reciprocity \nJoint supervision of master's and doctoral theses",
			"Coordinating faculty member": "DOIA\nDOAA\nDOFA",
			"Signed on": "March 14, 2019",
			Duration: "5 Years",
			"Country with which there is collation": "France",
		},
		{
			"S.No.": 8,
			"Institutions/Organization/Country": "University of Strasbourg, France",
			Nature: "MoU",
			"Purpose/Title":
				"Exchange of faculty members, researchers, administrative staff\nExchange of students \nJoint supervision of thesis\nDevelopment of joint research projects\nOrganization of mutual courses and joint seminars",
			"Coordinating faculty member": "DOIA\nDOAA\nDr. I. A. Palani",
			"Signed on": "June 13, 2018",
			Duration: "2 Years",
			"Country with which there is collation": "France",
		},
		{
			"S.No.": 9,
			"Institutions/Organization/Country": "ECAM Lyon, France",
			Nature: "MoU",
			"Purpose/Title":
				"Exchange of faculty members, Research Scientists, Postdoctoral Associates and administrative staff\nExchange of students (undergraduate and/or graduate)\nJoint supervision of M.S. and Ph.D. students\nDevelopment of curricula\nExchange of academic information and materials Exchange of periodicals and other publications\nOrganization of joint research programs, conferences",
			"Coordinating faculty member": "DOIA\nDOAA\nDOFA",
			"Signed on": "May 23, 2018",
			Duration: "5 Years",
			"Country with which there is collation": "France",
		},
		{
			"S.No.": 10,
			"Institutions/Organization/Country":
				"Ecole Nationale Superieure Mines-Telecom Atlantique Bretagne Pays Dela Loire( IMT Atlantique )",
			Nature: "MoU",
			"Purpose/Title":
				"Students, Faculty and Administrative staff exchange, Joint supervision of M.S. and PhDStudents, Exchanges of academic materials",
			"Coordinating faculty member": "DOIA\nDOAA\nDr. Vinod Kumar",
			"Signed on": "March 10, 2018",
			Duration: "5 Years",
			"Country with which there is collation": "France",
		},
		{
			"S.No.": 11,
			"Institutions/Organization/Country":
				"Department of Engineering, University of Messina, Italy",
			Nature: "MoU",
			"Purpose/Title":
				"Students and academic and administrative staff exchanges;\nJoint research activities;\nExchanges of academic materials",
			"Coordinating faculty member": "DOAA\nDOIA",
			"Signed on": "March 05, 2018",
			Duration: "Till consent",
			"Country with which there is collation": "Italy",
		},
		{
			"S.No.": 12,
			"Institutions/Organization/Country":
				"University of Stuttgart, Germany (on behalf of TU9 Universities, Germany)",
			Nature: "MoU",
			"Purpose/Title":
				"Academic and Research collaboration in areas of mutual interest;\nExchange of academic information, scholarly information, materials, and publications;\nExchange of students, research scientists, postdoctoral associates, and faculty members;\nSponsorship of cooperative seminars, workshops, and other academic meetings.",
			"Coordinating faculty member": "DOIA\nDOAA\nDr. Parashram M. Shirage",
			"Signed on": "January 8, 2018",
			Duration: "5 Years",
			"Country with which there is collation": "Germany",
		},
		{
			"S.No.": 13,
			"Institutions/Organization/Country":
				"The Universite Catholique De Louvain( Louvain-LA-Neuve, Belgium)",
			Nature: "Cooperation Agreement",
			"Purpose/Title":
				"Planning, development, and implementation of \nExchange programs for senior and assistant teaching staff, researchers, and students;\nJoint research program;\nThe exchange of scientific information",
			"Coordinating faculty member": "DOIA\nDOAA\nDr. Rupesh S. Devan",
			"Signed on": "November 08, 2017",
			Duration: "5 Years",
			"Country with which there is collation": "Belgium",
		},
		{
			"S.No.": 14,
			"Institutions/Organization/Country": "Technische Universität Dresden’s (TUD), Germany",
			Nature: "MoU",
			"Purpose/Title":
				"Students, Faculty and Administrative staff exchange, Joint supervision of M.S. and Ph.D. students, Exchanges of academic materials",
			"Coordinating faculty member": "DOIA \nDOAA\nDr. Somaditya Sen",
			"Signed on": "November 7, 2016",
			Duration: "5 Years",
			"Country with which there is collation": "Germany",
		},
		{
			"S.No.": 15,
			"Institutions/Organization/Country":
				"Max Planck Institute For Dynamics Of Complex Technical Systems (Mpi), Magdeburg, Germany",
			Nature: "MoU",
			"Purpose/Title":
				"Students, Faculty and Administrative staff exchange, Joint supervision of M.S. and Ph.D. students, Exchanges of academic materials",
			"Coordinating faculty member": "DOAA\nDOIA\nDOFA",
			"Signed on": "November 3, 2016",
			Duration: "5 Years",
			"Country with which there is collation": "Germany",
		},
		{
			"S.No.": 16,
			"Institutions/Organization/Country":
				"Technische Universität Berlin (TU Berlin), Germany",
			Nature: "MOU",
			"Purpose/Title":
				"Students, Faculty and Administrative staff exchange, Joint supervision of M.S. and Ph.D. students, Exchanges of academic materials",
			"Coordinating faculty member": "DOAA\nDOIA\nDOFA",
			"Signed on": "November 2, 2016",
			Duration: "5 Years",
			"Country with which there is collation": "Germany",
		},
		{
			"S.No.": 17,
			"Institutions/Organization/Country": "Leibniz Universität Hannover, Germany",
			Nature: "MoU",
			"Purpose/Title":
				"Students and academic and administrative staff exchanges;\nJoint research activities;\nExchanges of academic materials",
			"Coordinating faculty member": "DOAA\nDOIA\nDOFA",
			"Signed on": "October 28, 2016",
			Duration: "Initially for 3 Years",
			"Country with which there is collation": "Germany",
		},
		{
			"S.No.": 18,
			"Institutions/Organization/Country": "Ubiquity Press Limited, London",
			Nature: "MoU",
			"Purpose/Title": "Academics",
			"Coordinating faculty member": "DOAA\nDOIA\nDOFA",
			"Signed on": "June 30, 2016",
			Duration: "3 Years",
			"Country with which there is collation": "London",
		},
		{
			"S.No.": 19,
			"Institutions/Organization/Country":
				"Kurnakov Institute of General and Inorganic Chemistry of the Russian Academy of Sciences (IGIC RAS), Russia",
			Nature: "MoU",
			"Purpose/Title": "Academic",
			"Coordinating faculty member": "DOIA\nDOAA\nDr. Somaditya Sen",
			"Signed on": "",
			Duration: "3 Years (with automatic prolongation for the next one Year)",
			"Country with which there is collation": "Russia",
		},
		{
			"S.No.": 20,
			"Institutions/Organization/Country":
				"Technische Universität Braunschweig (TU Braunschweig), Braunschweig, Germany",
			Nature: "MoU",
			"Purpose/Title": "Academic and Research",
			"Coordinating faculty member": "DOIA\nDOAA",
			"Signed on": "October 1, 2015",
			Duration: "5 Years",
			"Country with which there is collation": "Germany",
		},
		{
			"S.No.": 21,
			"Institutions/Organization/Country": "RWTH Aachen University, Germany",
			Nature: "MoU",
			"Purpose/Title": "Teaching and Research",
			"Coordinating faculty member": "DOIA\nDOAA\nDORD",
			"Signed on": "September 14, 2015",
			Duration: "5 Years",
			"Country with which there is collation": "Germany",
		},
		{
			"S.No.": 22,
			"Institutions/Organization/Country": "Universitat Rovira l Virgili, Spain",
			Nature: "MoU",
			"Purpose/Title": "Mobility Programmes for teaching and research staff",
			"Coordinating faculty member": "DOIA\nDOAA\nDr. Sudeshna Chattopadhyay",
			"Signed on": "June 1, 2015",
			Duration: "1 Year",
			"Country with which there is collation": "Spain",
		},
		{
			"S.No.": 23,
			"Institutions/Organization/Country": "INSTITUT Mines -Telecom, France",
			Nature: "MoU",
			"Purpose/Title": "Academic and Scientific Collaboration",
			"Coordinating faculty member": "DOIA\nDORD",
			"Signed on": "October 25, 2013",
			Duration: "5 Years",
			"Country with which there is collation": "France",
		},
		{
			"S.No.": 24,
			"Institutions/Organization/Country": "ALICE Collaboration, CERN, Geneva",
			Nature: "MoU",
			"Purpose/Title":
				"For Collaboration in the Construction, the Maintenance and Operation of the ALICE Detector",
			"Coordinating faculty member": "DOIA\nDOAA",
			"Signed on": "May 2, 2013",
			Duration: "10 Years",
			"Country with which there is collation": "Geneva",
		},
		{
			"S.No.": 25,
			"Institutions/Organization/Country": "Keele University, UK",
			Nature: "MoU",
			"Purpose/Title": "Academic",
			"Coordinating faculty member": "DOIA\nDOAA",
			"Signed on": "October 31, 2012",
			Duration: "Initially 5 Years",
			"Country with which there is collation": "UK",
		},
		{
			"S.No.": 26,
			"Institutions/Organization/Country":
				"Fraunhofer  - Gesellschaft zur Forderung der Angewandten Forschung, Germany",
			Nature: "MoU",
			"Purpose/Title": "Academic",
			"Coordinating faculty member": "DOIA\nDOAA",
			"Signed on": "October 30, 2012",
			Duration: "5 Years",
			"Country with which there is collation": "Germany",
		},
		{
			"S.No.": 27,
			"Institutions/Organization/Country":
				"Ecole Internationale Des Sciences Du Traitement De L'Information-France",
			Nature: "MoU",
			"Purpose/Title": "Academic",
			"Coordinating faculty member": "DOIA\nDOAA\nDr. Vipul Singh",
			"Signed on": "May 21, 2012",
			Duration: "Till consent",
			"Country with which there is collation": "France",
		},
		{
			"S.No.": 28,
			"Institutions/Organization/Country": "Saarland University, Germany",
			Nature: "MoU",
			"Purpose/Title": "Student Exchange Programme",
			"Coordinating faculty member": "DOIA\nDOAA",
			"Signed on": "November 12, 2010",
			Duration: "Initially 5 Years",
			"Country with which there is collation": "Germany",
		},
	],
};
