export const data = {
	Asia: [
		{
			"S.No.": "1",
			"Institutions/Organization/Country": "Shinshu University, Matsumoto",
			Nature: "MoU",
			"Purpose/Title": "Academic Cooperation and Exchange of students",
			"Coordinating faculty member": "DOIA\r\nDOAA",
			"Signed on": "July 28, 2020",
			Duration: "5 Years",
			"Country with which there is collation": "Japan",
		},
		{
			"S.No.": "2",
			"Institutions/Organization/Country": "Rajamangala University of Technology PHRA Nakhon, Bangkok",
			Nature: "MoU",
			"Purpose/Title":
				"Exchanging of scholars, students, academic information and materials to enhance the research and educational process",
			"Coordinating faculty member": "DOIA\r\nDOAA\r\nDORD",
			"Signed on": "February 20,2020",
			Duration: "5 Years",
			"Country with which there is collation": "Thailand",
		},
		{
			"S.No.": "3",
			"Institutions/Organization/Country": "Thammsasat University, Bangkok",
			Nature: "MoU",
			"Purpose/Title":
				"Exchange of students, scholars, researchers and staff;\r\nCollaborative activities such as joint research, lectures, and symposium; \r\nSharing of information, publications, documents, and research materials in fields of mutual interest;\r\nOther mutually beneficial Projects;",
			"Coordinating faculty member": "DOIA\r\nDORD\r\nHOD, CE",
			"Signed on": "December 24, 2019",
			Duration: "5 Years",
			"Country with which there is collation": "Thailand",
		},
		{
			"S.No.": "4",
			"Institutions/Organization/Country": "Chonnam National University, Gwangju",
			Nature: "MoU",
			"Purpose/Title": "Cooperation in Academic and Research Related Activities;",
			"Coordinating faculty member": "DOIA\r\nDOAA\r\nDOFA\r\nDORD",
			"Signed on": "March 15, 2018",
			Duration: "5 Years",
			"Country with which there is collation": "South Korea",
		},
		{
			"S.No.": "5",
			"Institutions/Organization/Country": "Nagaoka University of Technology, Nagaoka",
			Nature: "Agreement",
			"Purpose/Title":
				"The exchange of academic, research, and administrative staffs; \r\nThe exchange of students; \r\nJoint research on scientific and technological subjects; \r\nJoint scientific and technological meetings, symposiums, workshops, conferences, and lectures; \r\nThe exchange of academic findings, publications, and other academic and educational information as appropriate; \r\nand  Other academic and educational collaboration and exchange as approved by the two universities/ institutes.",
			"Coordinating faculty member": "DOIA\r\nDOAA",
			"Signed on": "July 6, 2018",
			Duration: "5 Years",
			"Country with which there is collation": "Japan",
		},
		{
			"S.No.": "6",
			"Institutions/Organization/Country":
				"Graduate School of Life Science and Systems Engineering, Kyushu Institute of Technology, Fukuoka",
			Nature: "MoU",
			"Purpose/Title":
				"Exchange of students, faculty members for research, discussion and lectures; \r\nJoint research activities; \r\nExchanges of academic materials",
			"Coordinating faculty member": "DOIA\r\nDOAA\r\nDOFA",
			"Signed on": "April 18, 2018",
			Duration: "5 Years",
			"Country with which there is collation": "Japan",
		},
		{
			"S.No.": "7",
			"Institutions/Organization/Country": "National Dong Hwa University, Hualien County",
			Nature: "MoU",
			"Purpose/Title":
				"Students and academic and administrative staff exchanges; \r\nJoint research activities; \r\nExchanges of academic materials",
			"Coordinating faculty member": "DOIA\r\nDOAA\r\nDORD",
			"Signed on": "November 24, 2017",
			Duration: "",
			"Country with which there is collation": "Taiwan",
		},
		{
			"S.No.": "8",
			"Institutions/Organization/Country": "Jeju National University, Jeju City",
			Nature: "MoU",
			"Purpose/Title": "Academics",
			"Coordinating faculty member": "DOIA\r\nDr. Shaibal Mukherjee",
			"Signed on": "June 26, 2017",
			Duration: "5 Years",
			"Country with which there is collation": "South Korea",
		},
		{
			"S.No.": "9",
			"Institutions/Organization/Country": "Ming Chi University Of Technology, New Taipei City",
			Nature: "MoU",
			"Purpose/Title":
				"Academic and Research Collaboration, Scholarship Program to Ph.D. students       \r\nunder Joint Supervision",
			"Coordinating faculty member": "DOIA\r\nDOAA\r\nDr. I. A. Palani",
			"Signed on": "May 8, 2017",
			Duration: "5 Years",
			"Country with which there is collation": "Taiwan",
		},
		{
			"S.No.": "10",
			"Institutions/Organization/Country": "Enricssion Co. Ltd., Kyoto",
			Nature: "MoU",
			"Purpose/Title": "Establishment of Shiru Café at IIT",
			"Coordinating faculty member": "DOAA\r\nHOS, HSS",
			"Signed on": "March 4, 2016",
			Duration: "",
			"Country with which there is collation": "Japan",
		},
		{
			"S.No.": "11",
			"Institutions/Organization/Country": "Ming Chi University of Technology, New Taipei",
			Nature: "MoU",
			"Purpose/Title": "Academic and Research Collaboration",
			"Coordinating faculty member": "Registrar",
			"Signed on": "Febrary 11, 2016",
			Duration: "5 Years",
			"Country with which there is collation": "Taiwan",
		},
		{
			"S.No.": "12",
			"Institutions/Organization/Country": "Kyushu Institute of Technology, Kitakyushu",
			Nature: "MoU",
			"Purpose/Title": "Academic",
			"Coordinating faculty member": "DOIA\r\nDOAA",
			"Signed on": "June 11, 2012",
			Duration: "5 Years",
			"Country with which there is collation": "Japan",
		},
	],

	Americas: [
		{
			"Institutions/Organization/Country": "The Governors of The University of Alberta",
			Nature: "MoU",
			"Purpose/Title":
				"Exchange of faculty members, research scientists, and postdoctoral associates\n• Exchange of students\n• Exchange of administrative staff\n• Joint supervision of M.S. and Ph.D. students\n• Development of curricula\n• Exchange of academic information and materials\n• Exchange of periodicals and other publications\n• Submission and execution of joint research programs\n• Organization of joint research programs\n• Organization of joint conferences\n• Organization of other academic exchanges agreeable to both Institute(s)/University",
			"Coordinating faculty member": "DOIAO",
			"Signed on": "May 25, 2021",
			Duration: "5 Years",
			"Country with which there is collation": "Canada",
		},
		{
			"Institutions/Organization/Country": "Fundacao University Of Caxias Do Sul, Caxias Do Sul",
			Nature: "MoU",
			"Purpose/Title":
				"Exchange programs for Professors, Researchers, Students, Administrators, and technical person;\r\nJoint development of projects and research;\r\nDevelopment of scholarship programs;\r\nActivities of attainment of graduate and Post-graduate academic levels.\r\nExchange of bibliography, programs, didactic, technical and scientific material;\r\nElaboration of scientific articles and other publications;\r\nOther forms of cooperation agreed by the parties.",
			"Coordinating faculty member": "Dr. Bhupesh Lad",
			"Signed on": "Febrary 12, 2019",
			Duration: "5 Years",
			"Country with which there is collation": "Brazil",
		},
		{
			"Institutions/Organization/Country": "Oregon State University, Corvallis",
			Nature: "MoU",
			"Purpose/Title":
				"Exchange of students, faculty members for research, discussion, and lectures;\r\nJoint research activities;\r\nExchanges of academic materials",
			"Coordinating faculty member": "DOIA\r\nDOAA\r\nDORF\r\nDr. Rupesh S. Devan",
			"Signed on": "May 15, 2018",
			Duration: "5 Years",
			"Country with which there is collation": "USA",
		},
		{
			"Institutions/Organization/Country": "UT-Battelle, LLC",
			Nature: "Non-Proprietary User Agreement",
			"Purpose/Title":
				'The operator of Oak Ridge National Laboratory ( hereinafter "Laboratory" or "ORNL" under Prime contract No. DE-AC05-00OR22725 with the United States Government( hereinafter "U.S. Government" or "Government"), as represented by the United States Department of Energy (hereinafter "DOE") and IIT Indore',
			"Coordinating faculty member": "DOIA\r\nDOAA\r\nDORD",
			"Signed on": "July 27, 2017",
			Duration: "5 Years",
			"Country with which there is collation": "USA",
		},
		{
			"Institutions/Organization/Country": "The University of Wiscosin, Madison",
			Nature: "MoU",
			"Purpose/Title": "Specific Astro Physical Research Projects",
			"Coordinating faculty member": "DOIA\r\nDOAA",
			"Signed on": "January 28, 2013",
			Duration: "10 Years",
			"Country with which there is collation": "USA",
		},
		{
			"Institutions/Organization/Country": "Uchicago, Argonne LLC, IL",
			Nature: "MoU",
			"Purpose/Title": "Academic",
			"Coordinating faculty member": "DOIA\r\nDORD\r\nHOD, AASSE",
			"Signed on": "December 5, 2012",
			Duration: "5 Years",
			"Country with which there is collation": "USA",
		},
		{
			"Institutions/Organization/Country": "University of Milwaukee, Wisconsin",
			Nature: "MoU",
			"Purpose/Title": "Academic",
			"Coordinating faculty member": "DOIA\r\nDOAA",
			"Signed on": "October 3, 2012",
			Duration: "Till mutually agreed",
			"Country with which there is collation": "USA",
		},
		{
			"Institutions/Organization/Country": "New Mexico State University, Las Cruces",
			Nature: "MoU",
			"Purpose/Title": "Academic",
			"Coordinating faculty member": "DOIA\r\nDOAA",
			"Signed on": "October 1, 2012",
			Duration: "5 Years",
			"Country with which there is collation": "USA",
		},
	],
	Australia: [
		{
			"S.No.": "1",
			"Institutions/Organization/Country": "University of Technology, Ultimo",
			Nature: "MoU",
			"Purpose/Title":
				"Visits by and exchange of students for the purpose of research; Visits by interchange of staff for the purposes of research, teaching, and discussions;\r\nJoint research activities; \r\nJoint participation in internationally funded research projects;",
			"Coordinating faculty member": "DOIA\r\nDOAA\r\nDORD",
			"Signed on": "October 24, 2019",
			Duration: "5 Years",
			"Country with which there is collation": "Australia",
		},
		{
			"S.No.": "2",
			"Institutions/Organization/Country": "Edith Cowan University, Joondalup",
			Nature: "MoU",
			"Purpose/Title":
				"Research visit of faculty members, Research Scientists, Postdoctoral Associates, and students \r\nJoint supervision of M.S. and Ph.D. students\r\nDevelopment of curricula\r\nPromote international cooperation and academic exchange",
			"Coordinating faculty member": "DOIA\r\nDOAA\r\nDr. Bhargava Vaidya",
			"Signed on": "May 23, 2019",
			Duration: "5 Years",
			"Country with which there is collation": "Australia",
		},
		{
			"S.No.": "3",
			"Institutions/Organization/Country": "Deakin University, Geelong",
			Nature: "MoU",
			"Purpose/Title": "Research activities, possible short-course programs and joint research degree",
			"Coordinating faculty member": "DOIA\r\nDORD\r\nDr. Raghunath Sahoo",
			"Signed on": "March 6, 2013",
			Duration: "5 Years",
			"Country with which there is collation": "Australia",
		},
	],
	Europe: [
		{
			"S.No.": "1",
			"Institutions/Organization/Country": "Universitàdeglistudi Di Udine",
			Nature: "MoU",
			"Purpose/Title":
				"a) exchange of information, as well as exchange of experiences in research and practice in cooperation\nb) joint events, conferences, workshops and presentations with the goal of exchanging of scientific and technical experiences\nc) development, acquisition and conducting of joint projects\nd) joint publications by co-workers of both the Institutes\ne) exchange of co-workers from both the Institutes",
			"Coordinating faculty member": "DOIAO\r\nDr. Neelima Satyam",
			"Signed on": "May 24, 2021",
			Duration: "5 Years",
			"Country with which there is collation": "Italy",
		},
		{
			"S.No.": "1",
			"Institutions/Organization/Country":
				"The faculty of Electrical Engineering, Computer Science and Information Technology Osijek, within Josip Juraj Strossmayer University of Osijek",
			Nature: "MoU",
			"Purpose/Title": "General agreement for academic, scientific, technological and cultural cooperation",
			"Coordinating faculty member": "Director\r\nDOIAO",
			"Signed on": "May 24, 2021",
			Duration: "5 Years",
			"Country with which there is collation": "Croatia",
		},
		{
			"S.No.": "2",
			"Institutions/Organization/Country":
				"Dipartimento di Scienze Biomedichedell’ Università di Sassari (UNISS); Sassari, Italy",
			Nature: "MoU",
			"Purpose/Title": "Academic collaboration",
			"Coordinating faculty member": "Director\r\nDOIAO",
			"Signed on": "April 9, 2021",
			Duration: "5 years",
			"Country with which there is collation": "Italy",
		},
		{
			"S.No.": "1",
			"Institutions/Organization/Country": "Western Norway Research Institute, Sogndal",
			Nature: "Agreement",
			"Purpose/Title":
				"Transnational Partnership for Excellent Research and Education in Disruptive Technologies for a resilient future",
			"Coordinating faculty member": "DORD\r\nDr. Abhishek Srivastava, CSE",
			"Signed on": "August 11, 2020",
			Duration: "3 Years",
			"Country with which there is collation": "Norway",
		},
		{
			"S.No.": "2",
			"Institutions/Organization/Country": "University of Florence, Florence",
			Nature: "Agreement",
			"Purpose/Title": "Cultural and Scientific Cooperation between the dept of earth sciences",
			"Coordinating faculty member": "DOIA\r\nDORD\r\nHOD, CE",
			"Signed on": "December 23, 2019",
			Duration: "7 years",
			"Country with which there is collation": "Italy",
		},
		{
			"S.No.": "3",
			"Institutions/Organization/Country": "National Polytechnic Institute of Toulouse, Toulouse",
			Nature: "Agreement",
			"Purpose/Title":
				"Exchange of materials in education and research, in particular, to promote international information;\r\nExchange of faculty members and Research Scholars;\r\nOne way exchange of students;\r\nJoint research and meetings for education and research;\r\nTechnical assistance;\r\nUtilizing a hybrid online learning model for graduate training;",
			"Coordinating faculty member": "DOIA\r\nDOAA",
			"Signed on": "October 23, 2019",
			Duration: "5 Years",
			"Country with which there is collation": "France",
		},
		{
			"S.No.": "4",
			"Institutions/Organization/Country": "Max Planck Institute for Astronomy, Heidelberg",
			Nature: "Collaborative Agreement",
			"Purpose/Title":
				"To perform collaborative research activities according to the collaborative research program",
			"Coordinating faculty member": "DOIA\r\nDOAA\r\nDr. Bhargava Vaidya",
			"Signed on": "July 1, 2019",
			Duration: "3 Years",
			"Country with which there is collation": "Germany",
		},
		{
			"S.No.": "5",
			"Institutions/Organization/Country": "Uppsala University, Sweden",
			Nature: "MoU",
			"Purpose/Title":
				"Exchange of faculty members, Postdoctoral Associates, Research Scholars, and Master Students\r\nJoint supervision of M.S. and Ph.D. students\r\nDevelopment of curricula\r\nExchange of academic information and materials Exchange of periodicals and other publications\r\nOrganization of joint research programs, conferences",
			"Coordinating faculty member": "DOIA\r\nDOAA\r\nHOD, HSS",
			"Signed on": "April 24, 2019",
			Duration: "5 Years",
			"Country with which there is collation": "Sweden",
		},
		{
			"S.No.": "6",
			"Institutions/Organization/Country": "Royal Academy of Engineering, London",
			Nature: "MoU",
			"Purpose/Title":
				"To support the aims of the UK government’s Newton Fund by facilitating international visits and exchanges between industry and academic partners in the UK and their counterparts in elected Newton Fund Partner Countries",
			"Coordinating faculty member": "DOIA\r\nDOAA\r\nHOD, Chemistry",
			"Signed on": "March 14, 2019",
			Duration: "2 Years",
			"Country with which there is collation": "UK",
		},
		{
			"S.No.": "7",
			"Institutions/Organization/Country": "INSTITUT Mines-Telecom, Palaiseau",
			Nature: "MoU",
			"Purpose/Title":
				"To foster academic and scientific collaboration  \r\nProvide opportunity for global experience \r\nFacilitate the advancement of knowledge on the basis of reciprocity \r\nJoint supervision of master's and doctoral theses",
			"Coordinating faculty member": "DOIA\r\nDOAA\r\nDOFA",
			"Signed on": "March 14, 2019",
			Duration: "5 Years",
			"Country with which there is collation": "France",
		},
		{
			"S.No.": "8",
			"Institutions/Organization/Country": "University of Strasbourg, Strasbourg",
			Nature: "MoU",
			"Purpose/Title":
				"Exchange of faculty members, researchers, administrative staff\r\nExchange of students \r\nJoint supervision of thesis\r\nDevelopment of joint research projects\r\nOrganization of mutual courses and joint seminars",
			"Coordinating faculty member": "DOIA\r\nDOAA\r\nDr. I. A. Palani",
			"Signed on": "June 13, 2018",
			Duration: "2 Years",
			"Country with which there is collation": "France",
		},
		{
			"S.No.": "9",
			"Institutions/Organization/Country": "ECAM, Lyon",
			Nature: "MoU",
			"Purpose/Title":
				"Exchange of faculty members, Research Scientists, Postdoctoral Associates and administrative staff\r\nExchange of students (undergraduate and/or graduate)\r\nJoint supervision of M.S. and Ph.D. students\r\nDevelopment of curricula\r\nExchange of academic information and materials Exchange of periodicals and other publications\r\nOrganization of joint research programs, conferences",
			"Coordinating faculty member": "DOIA\r\nDOAA\r\nDOFA",
			"Signed on": "May 23, 2018",
			Duration: "5 Years",
			"Country with which there is collation": "France",
		},
		{
			"S.No.": "10",
			"Institutions/Organization/Country": "IMT Atlantique, Nantes",
			Nature: "MoU",
			"Purpose/Title":
				"Students, Faculty and Administrative staff exchange, Joint supervision of M.S. and PhDStudents, Exchanges of academic materials",
			"Coordinating faculty member": "DOIA\r\nDOAA\r\nDr. Vinod Kumar",
			"Signed on": "March 10, 2018",
			Duration: "5 Years",
			"Country with which there is collation": "France",
		},
		{
			"S.No.": "11",
			"Institutions/Organization/Country": "Department of Engineering, University of Messina, Messina",
			Nature: "MoU",
			"Purpose/Title":
				"Students and academic and administrative staff exchanges;\r\nJoint research activities;\r\nExchanges of academic materials",
			"Coordinating faculty member": "DOAA\r\nDOIA",
			"Signed on": "March 05, 2018",
			Duration: "Till consent",
			"Country with which there is collation": "Italy",
		},
		{
			"S.No.": "12",
			"Institutions/Organization/Country": "University of Stuttgart, Stuttgart",
			Nature: "MoU",
			"Purpose/Title":
				"Academic and Research collaboration in areas of mutual interest;\r\nExchange of academic information, scholarly information, materials, and publications;\r\nExchange of students, research scientists, postdoctoral associates, and faculty members;\r\nSponsorship of cooperative seminars, workshops, and other academic meetings.",
			"Coordinating faculty member": "DOIA\r\nDOAA\r\nDr. Parashram M. Shirage",
			"Signed on": "January 8, 2018",
			Duration: "5 Years",
			"Country with which there is collation": "Germany",
		},
		{
			"S.No.": "13",
			"Institutions/Organization/Country": "The Catholic University of Louvain, Belgium",
			Nature: "Cooperation Agreement",
			"Purpose/Title":
				"Planning, development, and implementation of \r\nExchange programs for senior and assistant teaching staff, researchers, and students;\r\nJoint research program;\r\nThe exchange of scientific information",
			"Coordinating faculty member": "DOIA\r\nDOAA\r\nDr. Rupesh S. Devan",
			"Signed on": "November 08, 2017",
			Duration: "5 Years",
			"Country with which there is collation": "Belgium",
		},
		{
			"S.No.": "14",
			"Institutions/Organization/Country": "Technical University Dresden’s (TUD), Dresden",
			Nature: "MoU",
			"Purpose/Title":
				"Students, Faculty and Administrative staff exchange, Joint supervision of M.S. and Ph.D. students, Exchanges of academic materials",
			"Coordinating faculty member": "DOIA \r\nDOAA\r\nDr. Somaditya Sen",
			"Signed on": "November 7, 2016",
			Duration: "5 Years",
			"Country with which there is collation": "Germany",
		},
		{
			"S.No.": "15",
			"Institutions/Organization/Country":
				"Max Planck Institute For Dynamics Of Complex Technical Systems (Mpi), Magdeburg",
			Nature: "MoU",
			"Purpose/Title":
				"Students, Faculty and Administrative staff exchange, Joint supervision of M.S. and Ph.D. students, Exchanges of academic materials",
			"Coordinating faculty member": "DOAA\r\nDOIA\r\nDOFA",
			"Signed on": "November 3, 2016",
			Duration: "5 Years",
			"Country with which there is collation": "Germany",
		},
		{
			"S.No.": "16",
			"Institutions/Organization/Country": "Technical University Berlin (TU Berlin), Berlin",
			Nature: "MOU",
			"Purpose/Title":
				"Students, Faculty and Administrative staff exchange, Joint supervision of M.S. and Ph.D. students, Exchanges of academic materials",
			"Coordinating faculty member": "DOAA\r\nDOIA\r\nDOFA",
			"Signed on": "November 2, 2016",
			Duration: "5 Years",
			"Country with which there is collation": "Germany",
		},
		{
			"S.No.": "17",
			"Institutions/Organization/Country": "Leibniz University Hannover, Hannover",
			Nature: "MoU",
			"Purpose/Title":
				"Students and academic and administrative staff exchanges;\r\nJoint research activities;\r\nExchanges of academic materials",
			"Coordinating faculty member": "DOAA\r\nDOIA\r\nDOFA",
			"Signed on": "October 28, 2016",
			Duration: "Initially for 3 Years",
			"Country with which there is collation": "Germany",
		},
		{
			"S.No.": "18",
			"Institutions/Organization/Country": "Ubiquity Press Limited, London",
			Nature: "MoU",
			"Purpose/Title": "Academics",
			"Coordinating faculty member": "DOAA\r\nDOIA\r\nDOFA",
			"Signed on": "June 30, 2016",
			Duration: "3 Years",
			"Country with which there is collation": "UK",
		},
		{
			"S.No.": "19",
			"Institutions/Organization/Country":
				"Kurnakov Institute of General and Inorganic Chemistry of the Russian Academy of Sciences (IGIC RAS), Moscow",
			Nature: "MoU",
			"Purpose/Title": "Academic",
			"Coordinating faculty member": "DOIA\r\nDOAA\r\nDr. Somaditya Sen",
			"Signed on": "",
			Duration: "3 Years (with automatic prolongation for the next one Year)",
			"Country with which there is collation": "Russia",
		},
		{
			"S.No.": "20",
			"Institutions/Organization/Country": "Technical University of Braunschweig (TU Braunschweig), Braunschweig",
			Nature: "MoU",
			"Purpose/Title": "Academic and Research",
			"Coordinating faculty member": "DOIA\r\nDOAA",
			"Signed on": "October 1, 2015",
			Duration: "5 Years",
			"Country with which there is collation": "Germany",
		},
		{
			"S.No.": "21",
			"Institutions/Organization/Country": "RWTH Aachen University, Aachen",
			Nature: "MoU",
			"Purpose/Title": "Teaching and Research",
			"Coordinating faculty member": "DOIA\r\nDOAA\r\nDORD",
			"Signed on": "September 14, 2015",
			Duration: "5 Years",
			"Country with which there is collation": "Germany",
		},
		{
			"S.No.": "22",
			"Institutions/Organization/Country": "Rovira l Virgili University, Tarragona",
			Nature: "MoU",
			"Purpose/Title": "Mobility Programmes for teaching and research staff",
			"Coordinating faculty member": "DOIA\r\nDOAA\r\nDr. Sudeshna Chattopadhyay",
			"Signed on": "June 1, 2015",
			Duration: "1 Year",
			"Country with which there is collation": "Spain",
		},
		{
			"S.No.": "23",
			"Institutions/Organization/Country": "INSTITUT Mines -Telecom, Palaiseau",
			Nature: "MoU",
			"Purpose/Title": "Academic and Scientific Collaboration",
			"Coordinating faculty member": "DOIA\r\nDORD",
			"Signed on": "October 25, 2013",
			Duration: "5 Years",
			"Country with which there is collation": "France",
		},
		{
			"S.No.": "24",
			"Institutions/Organization/Country": "ALICE Collaboration, CERN, Geneva",
			Nature: "MoU",
			"Purpose/Title":
				"For Collaboration in the Construction, the Maintenance and Operation of the ALICE Detector",
			"Coordinating faculty member": "DOIA\r\nDOAA",
			"Signed on": "May 2, 2013",
			Duration: "10 Years",
			"Country with which there is collation": "Geneva",
		},
		{
			"S.No.": "25",
			"Institutions/Organization/Country": "Keele University, Keele",
			Nature: "MoU",
			"Purpose/Title": "Academic",
			"Coordinating faculty member": "DOIA\r\nDOAA",
			"Signed on": "October 31, 2012",
			Duration: "Initially 5 Years",
			"Country with which there is collation": "UK",
		},
		{
			"S.No.": "26",
			"Institutions/Organization/Country": "Fraunhofer - Society for the Promotion of Applied Research, Munich",
			Nature: "MoU",
			"Purpose/Title": "Academic",
			"Coordinating faculty member": "DOIA\r\nDOAA",
			"Signed on": "October 30, 2012",
			Duration: "5 Years",
			"Country with which there is collation": "Germany",
		},
		{
			"S.No.": "27",
			"Institutions/Organization/Country":
				"International School of Information Processing Science, Cergy-Pontoise ",
			Nature: "MoU",
			"Purpose/Title": "Academic",
			"Coordinating faculty member": "DOIA\r\nDOAA\r\nDr. Vipul Singh",
			"Signed on": "May 21, 2012",
			Duration: "Till consent",
			"Country with which there is collation": "France",
		},
		{
			"S.No.": "28",
			"Institutions/Organization/Country": "Saarland University, Saarbrücken",
			Nature: "MoU",
			"Purpose/Title": "Student Exchange Programme",
			"Coordinating faculty member": "DOIA\r\nDOAA",
			"Signed on": "November 12, 2010",
			Duration: "Initially 5 Years",
			"Country with which there is collation": "Germany",
		},
	],
};
